### ISSUE TITLE
[BUG]  Spark-3.4 - Integration tests not starting due to recent change in CTAS

### ISSUE THREAD

**Issue by nartal1** [NVIDIA/spark-rapids#7433] opened 2022-12-29 04:34 UTC
**Describe the bug**
When Integration test is initiated on Spark-3.4, it throws below exception:
Failure is due to this commit which was merged recently on Apache Spark's master branch - https://github.com/apache/spark/commit/4b40920e33176fc8b18380703e4dcf4d16824094

```
  File "/home/nartal/apache-spark-3.4/spark-3.4.0-SNAPSHOT-bin-hadoop3.2-Dec28/python/lib/py4j-0.10.9.7-src.zip/py4j/clientserver.py", line 516, in send_command
    raise Py4JNetworkError("Answer from Java side is empty")
py4j.protocol.Py4JNetworkError: Answer from Java side is empty

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/nartal/apache-spark-3.4/spark-3.4.0-SNAPSHOT-bin-hadoop3.2-Dec28/python/lib/py4j-0.10.9.7-src.zip/py4j/java_gateway.py", line 1038, in send_command
    response = connection.send_command(command)
  File "/home/nartal/apache-spark-3.4/spark-3.4.0-SNAPSHOT-bin-hadoop3.2-Dec28/python/lib/py4j-0.10.9.7-src.zip/py4j/clientserver.py", line 539, in send_command
    raise Py4JNetworkError(
py4j.protocol.Py4JNetworkError: Error while sending or receiving
2022-12-28 20:27:59 INFO     Closing down clientserver connection
22/12/29 04:27:59 ERROR RapidsExecutorPlugin: Exception in the executor plugin, shutting down!
java.lang.ExceptionInInitializerError
	at com.nvidia.spark.rapids.TypeChecks$.areTimestampsSupported(TypeChecks.scala:831)
	at com.nvidia.spark.rapids.RapidsExecutorPlugin.init(Plugin.scala:238)
	at org.apache.spark.internal.plugin.ExecutorPluginContainer.$anonfun$executorPlugins$1(PluginContainer.scala:125)
	at scala.collection.TraversableLike.$anonfun$flatMap$1(TraversableLike.scala:293)
	at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:62)
	at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:55)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:49)
	at scala.collection.TraversableLike.flatMap(TraversableLike.scala:293)
	at scala.collection.TraversableLike.flatMap$(TraversableLike.scala:290)
	at scala.collection.AbstractTraversable.flatMap(Traversable.scala:108)
	at org.apache.spark.internal.plugin.ExecutorPluginContainer.<init>(PluginContainer.scala:113)
	at org.apache.spark.internal.plugin.PluginContainer$.apply(PluginContainer.scala:211)
	at org.apache.spark.internal.plugin.PluginContainer$.apply(PluginContainer.scala:199)
	at org.apache.spark.executor.Executor.$anonfun$plugins$1(Executor.scala:285)
	at org.apache.spark.util.Utils$.withContextClassLoader(Utils.scala:240)
	at org.apache.spark.executor.Executor.<init>(Executor.scala:285)
	at org.apache.spark.scheduler.local.LocalEndpoint.<init>(LocalSchedulerBackend.scala:64)
	at org.apache.spark.scheduler.local.LocalSchedulerBackend.start(LocalSchedulerBackend.scala:132)
	at org.apache.spark.scheduler.TaskSchedulerImpl.start(TaskSchedulerImpl.scala:235)
	at org.apache.spark.SparkContext.<init>(SparkContext.scala:590)
	at org.apache.spark.api.java.JavaSparkContext.<init>(JavaSparkContext.scala:58)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:247)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:374)
	at py4j.Gateway.invoke(Gateway.java:238)
	at py4j.commands.ConstructorCommand.invokeConstructor(ConstructorCommand.java:80)
	at py4j.commands.ConstructorCommand.execute(ConstructorCommand.java:69)
	at py4j.ClientServerConnection.waitForCommands(ClientServerConnection.java:182)
	at py4j.ClientServerConnection.run(ClientServerConnection.java:106)
	at java.lang.Thread.run(Thread.java:750)
Caused by: java.lang.ClassCastException: class org.apache.spark.sql.execution.command.CreateDataSourceTableAsSelectCommand
	at java.lang.Class.asSubclass(Class.java:3404)
	at com.nvidia.spark.rapids.GpuOverrides$.$anonfun$commonDataWriteCmds$3(GpuOverrides.scala:3628)
	at scala.collection.immutable.List.map(List.scala:297)
	at com.nvidia.spark.rapids.GpuOverrides$.<init>(GpuOverrides.scala:3628)
	at com.nvidia.spark.rapids.GpuOverrides$.<clinit>(GpuOverrides.scala)
	... 33 more

``` 
**Steps/Code to reproduce bug**
Please provide a list of steps or a code sample to reproduce the issue.
~/spark-rapids/integration_tests$ ./run_pyspark_from_build.sh

**Expected behavior**
Tests should run

**Comment by HaoYang670** [comment] 2022-12-29 05:25
Relate to #7432

**Comment by sameerz** [comment] 2023-01-03 21:46
Duplicate of issue #7432

**Closed by sameerz** 2023-01-03 21:46 UTC
Labels: bug, duplicate, Spark 3.4+
