### ISSUE TITLE
[BUG] maven unit test crashed during regex test intermittently

### ISSUE THREAD

**Issue by pxLi** [NVIDIA/spark-rapids#8612] opened 2023-06-27 01:11 UTC
**Describe the bug**
We found test process crash in a pre-merge CI run of https://github.com/NVIDIA/spark-rapids/pull/8594

This failure seems to be not related to above change, but could be cudf-related
JNI commit: https://github.com/NVIDIA/spark-rapids-jni/commit/e8c87610db75b52e481ad34d98d643f739c29434, submodule cudf commit at https://github.com/rapidsai/cudf/commit/c7e9405f939d9750c6a6321fbd66c14674951042

core dump during maven test w/ 
`mvn -Dmaven.wagon.http.retryHandler.count=3 -U -B -Dbuildver=340 clean package -Drat.skip=true -Dskip -Dmaven.scalastyle.skip=true -Dcuda.version=cuda11` (not always reproducible)
```
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007f828b86d8df, pid=1108940, tid=0x00007f8294cb5700
#
# JRE version: OpenJDK Runtime Environment (8.0_362-b09) (build 1.8.0_362-8u372-ga~us1-0ubuntu1~20.04-b09)
# Java VM: OpenJDK 64-Bit Server VM (25.362-b09 mixed mode linux-amd64 compressed oops)
# Problematic frame:
# J 70853 C2 ai.rapids.cudf.ColumnView.copyToHost()Lai/rapids/cudf/HostColumnVector; (1738 bytes) @ 0x00007f828b86d8df [0x00007f828b86cc00+0xcdf]
#
# Core dump written. Default location: /home/jenkins/agent/workspace/jenkins-rapids_premerge-github-7397-ci-2/tests/core or core.1108940
#
# If you would like to submit a bug report, please visit:
#   http://bugreport.java.com/bugreport/crash.jsp
#

---------------  T H R E A D  ---------------

Current thread (0x00007f8290015000):  JavaThread "ScalaTest-main-running-RegularExpressionTranspilerSuite" [_thread_in_Java, id=1108943, stack(0x00007f82948b6000,0x00007f8294cb6000)]

siginfo: si_signo: 11 (SIGSEGV), si_code: 1 (SEGV_MAPERR), si_addr: 0x0000000000000018

Registers:
RAX=0x0000000000000000, RBX=0x000000000000006d, RCX=0x000000000000000b, RDX=0x000000078bf5d0b0
RSP=0x00007f8294cb1790, RBP=0x00000006c05a3f68, RSI=0x000000078bf5d0b0, RDI=0x0000000000000000
R8 =0x00000000d840571e, R9 =0x00000000d84327b4, R10=0x0000000000000000, R11=0x00000006c2326850
R12=0x0000000000000000, R13=0x0000000000000001, R14=0x0000000000000008, R15=0x00007f8290015000
RIP=0x00007f828b86d8df, EFLAGS=0x0000000000010206, CSGSFS=0x002b000000000033, ERR=0x0000000000000004
  TRAPNO=0x000000000000000e

Top of Stack: (sp=0x00007f8294cb1790)
0x00007f8294cb1790:   00007f8294cb17e0 00007f82819ff2e8
0x00007f8294cb17a0:   00000006c228f120 0000000000000000
0x00007f8294cb17b0:   00000007c0011600 00000007c042af08
0x00007f8294cb17c0:   00000006c17bc1b0 0000061600000616
0x00007f8294cb17d0:   000000078bf5d050 000000078bf5cf98
0x00007f8294cb17e0:   0000000000000000 d8451e24d82f7836
0x00007f8294cb17f0:   0000000000000000 000000078bf5bb48
0x00007f8294cb1800:   00000000000003e8 00000006c228f120
0x00007f8294cb1810:   d83ff1bbd82f78fb 00000006c17bc7d8
0x00007f8294cb1820:   00000027c8001000 00000003d83ff249
0x00007f8294cb1830:   000000060000001e 000000078bf5bb48
0x00007f8294cb1840:   00007f8294cb1880 00007f8294cb1870
0x00007f8294cb1850:   00007f7ecf81c2d0 00007f80851c0560
0x00007f8294cb1860:   000000078bf5cf70 00007f828b86cc20
0x00007f8294cb1870:   000000078bf5bb48 0000000000000206
0x00007f8294cb1880:   000000078bf5bb48 00007f8282cd8a8c
0x00007f8294cb1890:   00000006c17bc1b0 000000078bf5bb48
0x00007f8294cb18a0:   d8432718d82f7836 00000006c21938c0
0x00007f8294cb18b0:   0000000000000001 000000000000000b
0x00007f8294cb18c0:   00007f8294cb1930 0000000000000000
0x00007f8294cb18d0:   00000000d82f78fb 00007f828abd0be0
0x00007f8294cb18e0:   000000078bf5bb48 000002ecd82f78fb
0x00007f8294cb18f0:   00000047d818a1f1 00000006c17bc7d8
0x00007f8294cb1900:   00000006c0c50f88 00000006c391e110
0x00007f8294cb1910:   000000078bf5bb98 00007f8200000000
0x00007f8294cb1920:   00000006c00d4ad0 00007f8290015000
0x00007f8294cb1930:   000000078bf571f8 00007f8282ccd4bc
0x00007f8294cb1940:   00007f8290015000 00007f8295b087d8
0x00007f8294cb1950:   000000078bf5baf8 675bac7560eb7200
0x00007f8294cb1960:   0000000000000000 00007f80f5c42c40
0x00007f8294cb1970:   00007f8290015000 00007f8294cb4a90
0x00007f8294cb1980:   000000078bf5bb48 000000078bef9d10 

Instructions: (pc=0x00007f828b86d8df)
0x00007f828b86d8bf:   77 06 00 00 45 33 d2 83 fb 42 0f 86 ba 1b 00 00
0x00007f828b86d8cf:   4c 8b 54 24 50 4c 89 54 24 18 43 c6 44 c4 52 01
0x00007f828b86d8df:   4d 8b 4a 18 41 bb d7 e4 09 f8 49 ba 00 00 00 00
0x00007f828b86d8ef:   00 00 00 00 4f 8d 14 da 4c 89 94 24 80 00 00 00 

Register to memory mapping:

RAX=0x0000000000000000 is an unknown value
RBX=0x000000000000006d is an unknown value
RCX=0x000000000000000b is an unknown value
RDX=0x000000078bf5d0b0 is an oop
org.mockito.internal.util.concurrent.WeakConcurrentMap$LatentKey 
 - klass: 'org/mockito/internal/util/concurrent/WeakConcurrentMap$LatentKey'
RSP=0x00007f8294cb1790 is pointing into the stack for thread: 0x00007f8290015000
RBP=0x00000006c05a3f68 is an oop
org.mockito.internal.creation.bytebuddy.MockMethodAdvice 
 - klass: 'org/mockito/internal/creation/bytebuddy/MockMethodAdvice'
RSI=0x000000078bf5d0b0 is an oop
org.mockito.internal.util.concurrent.WeakConcurrentMap$LatentKey 
 - klass: 'org/mockito/internal/util/concurrent/WeakConcurrentMap$LatentKey'
RDI=0x0000000000000000 is an unknown value
R8 =0x00000000d840571e is an unknown value
R9 =0x00000000d84327b4 is an unknown value
R10=0x0000000000000000 is an unknown value
R11=0x00000006c2326850 is an oop
java.util.RegularEnumSet 
 - klass: 'java/util/RegularEnumSet'
R12=0x0000000000000000 is an unknown value
R13=0x0000000000000001 is an unknown value
R14=0x0000000000000008 is an unknown value
R15=0x00007f8290015000 is a thread


Stack: [0x00007f82948b6000,0x00007f8294cb6000],  sp=0x00007f8294cb1790,  free space=4077k
Native frames: (J=compiled Java code, j=interpreted, Vv=VM code, C=native code)
J 70853 C2 ai.rapids.cudf.ColumnView.copyToHost()Lai/rapids/cudf/HostColumnVector; (1738 bytes) @ 0x00007f828b86d8df [0x00007f828b86cc00+0xcdf]
J 70837 C1 com.nvidia.spark.rapids.RegularExpressionTranspilerSuite$$Lambda$13374.apply(Ljava/lang/Object;)Ljava/lang/Object; (12 bytes) @ 0x00007f8282cd8a8c [0x00007f8282cd87a0+0x2ec]
J 18194 C2 com.nvidia.spark.rapids.Arm$.withResource(Ljava/lang/AutoCloseable;Lscala/Function1;)Ljava/lang/Object; (78 bytes) @ 0x00007f8283054ca8 [0x00007f8283054700+0x5a8]
J 70831 C1 com.nvidia.spark.rapids.RegularExpressionTranspilerSuite.$anonfun$gpuContains$1(Ljava/lang/String;[ZLai/rapids/cudf/ColumnVector;)V (49 bytes) @ 0x00007f828ad4307c [0x00007f828ad42720+0x95c]
J 70829 C1 com.nvidia.spark.rapids.RegularExpressionTranspilerSuite$$Lambda$13366.apply(Ljava/lang/Object;)Ljava/lang/Object; (16 bytes) @ 0x00007f828b82df8c [0x00007f828b82dda0+0x1ec]
J 18194 C2 com.nvidia.spark.rapids.Arm$.withResource(Ljava/lang/AutoCloseable;Lscala/Function1;)Ljava/lang/Object; (78 bytes) @ 0x00007f8283054ca8 [0x00007f8283054700+0x5a8]
J 70820 C1 com.nvidia.spark.rapids.RegularExpressionTranspilerSuite.gpuContains(Ljava/lang/String;Lscala/collection/Seq;)[Z (62 bytes) @ 0x00007f828931e69c [0x00007f828931dee0+0x7bc]
J 70836 C1 com.nvidia.spark.rapids.RegularExpressionTranspilerSuite.$anonfun$assertCpuGpuMatchesRegexpFind$2(Lcom/nvidia/spark/rapids/RegularExpressionTranspilerSuite;Lscala/collection/Seq;Lscala/Tuple2;)V (275 bytes) @ 0x00007f8282cc894c [0x00007f8282cc82c0+0x68c]
J 70834 C1 com.nvidia.spark.rapids.RegularExpressionTranspilerSuite$$Lambda$13371.apply(Ljava/lang/Object;)Ljava/lang/Object; (16 bytes) @ 0x00007f8282cd9b4c [0x00007f8282cd9960+0x1ec]
J 18726 C2 scala.collection.TraversableLike$WithFilter$$Lambda$84.apply(Ljava/lang/Object;)Ljava/lang/Object; (13 bytes) @ 0x00007f8283156e30 [0x00007f8283156b60+0x2d0]
J 18622 C2 scala.collection.mutable.ArrayBuffer.foreach(Lscala/Function1;)V (6 bytes) @ 0x00007f82830f8ce8 [0x00007f82830f8c60+0x88]
J 35240 C2 scala.collection.TraversableLike$WithFilter.foreach(Lscala/Function1;)V (17 bytes) @ 0x00007f828638ed6c [0x00007f828638eca0+0xcc]
j  com.nvidia.spark.rapids.RegularExpressionTranspilerSuite.assertCpuGpuMatchesRegexpFind(Lscala/collection/Seq;Lscala/collection/Seq;)V+36
j  com.nvidia.spark.rapids.RegularExpressionTranspilerSuite.doFuzzTest(Lscala/Option;Lcom/nvidia/spark/rapids/RegexMode;)V+357
j  com.nvidia.spark.rapids.RegularExpressionTranspilerSuite.$anonfun$new$93(Lcom/nvidia/spark/rapids/RegularExpressionTranspilerSuite;)V+19
j  com.nvidia.spark.rapids.RegularExpressionTranspilerSuite$$Lambda$1827.apply$mcV$sp()V+4
J 22829 C2 scala.runtime.java8.JFunction0$mcV$sp.apply()Ljava/lang/Object; (10 bytes) @ 0x00007f82823bfb5c [0x00007f82823bfb20+0x3c]
J 62916 C1 org.scalatest.OutcomeOf.outcomeOf(Lscala/Function0;)Lorg/scalatest/Outcome; (143 bytes) @ 0x00007f828a77c18c [0x00007f828a77c080+0x10c]
J 62913 C1 org.scalatest.Transformer.apply()Ljava/lang/Object; (5 bytes) @ 0x00007f828a776e1c [0x00007f828a776c20+0x1fc]
J 63214 C1 org.scalatest.FunSuiteLike$$anon$1.apply()Lorg/scalatest/Outcome; (19 bytes) @ 0x00007f8282646584 [0x00007f8282646360+0x224]
J 60293 C1 org.scalatest.FunSuite.withFixture(Lorg/scalatest/TestSuite$NoArgTest;)Lorg/scalatest/Outcome; (6 bytes) @ 0x00007f82831c51ac [0x00007f82831c5020+0x18c]
J 63209 C1 org.scalatest.FunSuiteLike.invokeWithFixture$1(Lorg/scalatest/SuperEngine$TestLeaf;Ljava/lang/String;Lorg/scalatest/Args;)Lorg/scalatest/Outcome; (35 bytes) @ 0x00007f828407edc4 [0x00007f828407eb60+0x264]
J 63207 C1 org.scalatest.FunSuiteLike$$Lambda$1998.apply(Ljava/lang/Object;)Ljava/lang/Object; (20 bytes) @ 0x00007f82834fd91c [0x00007f82834fd760+0x1bc]
J 60263 C1 org.scalatest.SuperEngine.runTestImpl(Lorg/scalatest/Suite;Ljava/lang/String;Lorg/scalatest/Args;ZLscala/Function1;)Lorg/scalatest/Status; (1489 bytes) @ 0x00007f8289c440e4 [0x00007f8289c3f2c0+0x4e24]
J 59999 C1 org.scalatest.FunSuite.runTest(Ljava/lang/String;Lorg/scalatest/Args;)Lorg/scalatest/Status; (7 bytes) @ 0x00007f82834f0784 [0x00007f82834f02a0+0x4e4]
J 58730 C1 org.scalatest.FunSuiteLike$$Lambda$1992.apply(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object; (16 bytes) @ 0x00007f8283c4152c [0x00007f8283c41220+0x30c]
J 58726 C1 org.scalatest.SuperEngine.$anonfun$runTestsInBranch$1(Lorg/scalatest/SuperEngine;Lorg/scalatest/Suite;Lorg/scalatest/SuperEngine$Branch;Lorg/scalatest/Args;ZLscala/Function2;Lscala/collection/mutable/ListBuffer;Lorg/scalatest/SuperEngine$Node;)Ljava/lang/Object; (617 bytes) @ 0x00007f82894ab004 [0x00007f82894a9c80+0x1384]
J 58725 C1 org.scalatest.SuperEngine$$Lambda$1993.apply(Ljava/lang/Object;)Ljava/lang/Object; (36 bytes) @ 0x00007f82858b106c [0x00007f82858b0ec0+0x1ac]
J 17486 C2 scala.collection.immutable.List.foreach(Lscala/Function1;)V (32 bytes) @ 0x00007f8282e79cec [0x00007f8282e79c40+0xac]
j  org.scalatest.SuperEngine.traverseSubNodes$1(Lorg/scalatest/Suite;Lorg/scalatest/SuperEngine$Branch;Lorg/scalatest/Args;ZLscala/Function2;Lscala/collection/mutable/ListBuffer;)V+22
j  org.scalatest.SuperEngine.runTestsInBranch(Lorg/scalatest/Suite;Lorg/scalatest/SuperEngine$Branch;Lorg/scalatest/Args;ZLscala/Function2;)Lorg/scalatest/Status;+191
j  org.scalatest.SuperEngine.runTestsImpl(Lorg/scalatest/Suite;Lscala/Option;Lorg/scalatest/Args;Lorg/scalatest/Informer;ZLscala/Function2;)Lorg/scalatest/Status;+444
j  org.scalatest.FunSuiteLike.runTests(Lscala/Option;Lorg/scalatest/Args;)Lorg/scalatest/Status;+22
j  org.scalatest.FunSuiteLike.runTests$(Lorg/scalatest/FunSuiteLike;Lscala/Option;Lorg/scalatest/Args;)Lorg/scalatest/Status;+3
j  org.scalatest.FunSuite.runTests(Lscala/Option;Lorg/scalatest/Args;)Lorg/scalatest/Status;+3
j  org.scalatest.Suite.run(Lscala/Option;Lorg/scalatest/Args;)Lorg/scalatest/Status;+235
j  org.scalatest.Suite.run$(Lorg/scalatest/Suite;Lscala/Option;Lorg/scalatest/Args;)Lorg/scalatest/Status;+3
j  org.scalatest.FunSuite.org$scalatest$FunSuiteLike$$super$run(Lscala/Option;Lorg/scalatest/Args;)Lorg/scalatest/Status;+3
j  org.scalatest.FunSuiteLike.$anonfun$run$1(Lorg/scalatest/FunSuiteLike;Lscala/Option;Lorg/scalatest/Args;)Lorg/scalatest/Status;+3
j  org.scalatest.FunSuiteLike$$Lambda$1986.apply(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;+12
j  org.scalatest.SuperEngine.runImpl(Lorg/scalatest/Suite;Lscala/Option;Lorg/scalatest/Args;Lscala/Function2;)Lorg/scalatest/Status;+358
j  org.scalatest.FunSuiteLike.run(Lscala/Option;Lorg/scalatest/Args;)Lorg/scalatest/Status;+15
j  org.scalatest.FunSuiteLike.run$(Lorg/scalatest/FunSuiteLike;Lscala/Option;Lorg/scalatest/Args;)Lorg/scalatest/Status;+3
j  org.scalatest.FunSuite.run(Lscala/Option;Lorg/scalatest/Args;)Lorg/scalatest/Status;+3
j  org.scalatest.Suite.callExecuteOnSuite$1(Lorg/scalatest/Suite;Lorg/scalatest/Args;Lorg/scalatest/Reporter;)Lorg/scalatest/Status;+186
j  org.scalatest.Suite.$anonfun$runNestedSuites$1(Lorg/scalatest/Args;Lorg/scalatest/Reporter;Lscala/collection/mutable/ListBuffer;Lorg/scalatest/Suite;)Ljava/lang/Object;+16
j  org.scalatest.Suite$$Lambda$1984.apply(Ljava/lang/Object;)Ljava/lang/Object;+16
J 7097 C1 scala.collection.IndexedSeqOptimized.foreach(Lscala/Function1;)V (36 bytes) @ 0x00007f828163d5a4 [0x00007f828163d320+0x284]
J 7277 C1 scala.collection.mutable.ArrayOps$ofRef.foreach(Lscala/Function1;)V (6 bytes) @ 0x00007f8281527ffc [0x00007f8281527f40+0xbc]
j  org.scalatest.Suite.runNestedSuites(Lorg/scalatest/Args;)Lorg/scalatest/Status;+175
j  org.scalatest.Suite.runNestedSuites$(Lorg/scalatest/Suite;Lorg/scalatest/Args;)Lorg/scalatest/Status;+2
j  org.scalatest.tools.DiscoverySuite.runNestedSuites(Lorg/scalatest/Args;)Lorg/scalatest/Status;+2
j  org.scalatest.Suite.run(Lscala/Option;Lorg/scalatest/Args;)Lorg/scalatest/Status;+188
j  org.scalatest.Suite.run$(Lorg/scalatest/Suite;Lscala/Option;Lorg/scalatest/Args;)Lorg/scalatest/Status;+3
j  org.scalatest.tools.DiscoverySuite.run(Lscala/Option;Lorg/scalatest/Args;)Lorg/scalatest/Status;+3
j  org.scalatest.tools.SuiteRunner.run()V+184
j  org.scalatest.tools.Runner$.$anonfun$doRunRunRunDaDoRunRun$13(Lorg/scalatest/DispatchReporter;Lorg/scalatest/Stopper;Lscala/collection/immutable/Set;Lscala/collection/immutable/Set;Lorg/scalatest/ConfigMap;Lscala/collection/immutable/Set;Lscala/runtime/ObjectRef;Lorg/scalatest/tools/SuiteConfig;)V+173
j  org.scalatest.tools.Runner$.$anonfun$doRunRunRunDaDoRunRun$13$adapted(Lorg/scalatest/DispatchReporter;Lorg/scalatest/Stopper;Lscala/collection/immutable/Set;Lscala/collection/immutable/Set;Lorg/scalatest/ConfigMap;Lscala/collection/immutable/Set;Lscala/runtime/ObjectRef;Lorg/scalatest/tools/SuiteConfig;)Ljava/lang/Object;+12
j  org.scalatest.tools.Runner$$$Lambda$1982.apply(Ljava/lang/Object;)Ljava/lang/Object;+32
J 7994 C1 scala.collection.immutable.List.foreach(Lscala/Function1;)V (32 bytes) @ 0x00007f82817bad84 [0x00007f82817babc0+0x1c4]
j  org.scalatest.tools.Runner$.doRunRunRunDaDoRunRun(Lorg/scalatest/DispatchReporter;Lscala/collection/immutable/List;Lscala/collection/immutable/List;Lscala/collection/immutable/List;Lscala/collection/immutable/List;Lorg/scalatest/Stopper;Lscala/collection/immutable/Set;Lscala/collection/immutable/Set;Lorg/scalatest/ConfigMap;ZLscala/collection/immutable/List;Lscala/collection/immutable/List;Lscala/collection/immutable/List;Lscala/collection/immutable/List;Ljava/lang/ClassLoader;Lorg/scalatest/tools/RunDoneListener;ILorg/scalatest/tools/ConcurrentConfig;Lscala/Option;Lscala/collection/immutable/Set;)V+1430
j  org.scalatest.tools.Runner$.$anonfun$runOptionallyWithPassFailReporter$24(Lscala/Option;Lscala/collection/immutable/List;Lscala/collection/immutable/List;Lscala/collection/immutable/List;Lscala/collection/immutable/List;Lscala/collection/immutable/List;Lscala/collection/immutable/Set;Lscala/collection/immutable/Set;ZLorg/scalatest/tools/ConcurrentConfig;Lscala/collection/immutable/List;Lscala/collection/immutable/List;Lscala/collection/immutable/List;Lscala/collection/immutable/Set;Lorg/scalatest/ConfigMap;Ljava/lang/ClassLoader;Lorg/scalatest/DispatchReporter;)V+47
j  org.scalatest.tools.Runner$.$anonfun$runOptionallyWithPassFailReporter$24$adapted(Lscala/Option;Lscala/collection/immutable/List;Lscala/collection/immutable/List;Lscala/collection/immutable/List;Lscala/collection/immutable/List;Lscala/collection/immutable/List;Lscala/collection/immutable/Set;Lscala/collection/immutable/Set;ZLorg/scalatest/tools/ConcurrentConfig;Lscala/collection/immutable/List;Lscala/collection/immutable/List;Lscala/collection/immutable/List;Lscala/collection/immutable/Set;Lorg/scalatest/ConfigMap;Ljava/lang/ClassLoader;Lorg/scalatest/DispatchReporter;)Ljava/lang/Object;+30
j  org.scalatest.tools.Runner$$$Lambda$64.apply(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;+68
j  org.scalatest.tools.Runner$.withClassLoaderAndDispatchReporter(Lscala/collection/immutable/List;Lorg/scalatest/tools/ReporterConfigurations;Lscala/Option;Lscala/Option;ZJJLscala/Function2;)V+44
j  org.scalatest.tools.Runner$.runOptionallyWithPassFailReporter([Ljava/lang/String;Z)Z+1899
j  org.scalatest.tools.Runner$.main([Ljava/lang/String;)V+152
j  org.scalatest.tools.Runner.main([Ljava/lang/String;)V+4
v  ~StubRoutines::call_stub
V  [libjvm.so+0x6a5da5]
V  [libjvm.so+0x72735d]
V  [libjvm.so+0x729f2e]
C  [libjli.so+0x4802]
C  [libjli.so+0x8dc1]
C  [libpthread.so.0+0x8609]  start_thread+0xd9
```

**Steps/Code to reproduce bug**
Please provide a list of steps or a code sample to reproduce the issue.
Avoid posting private or sensitive data.

**Expected behavior**

**Environment details (please complete the following information)**
 - Environment location: [Standalone, YARN, Kubernetes, Cloud(specify cloud provider)]
 - Spark configuration settings related to the issue

**Additional context**

**Comment by jlowe** [comment] 2023-06-27 15:01
This looks like a duplicate of #8418.

**Closed** 2023-06-27 20:16 UTC
Labels: bug, duplicate, test
