### ISSUE TITLE
[FEA] test current_date and current_timestamp

### ISSUE THREAD

**Issue by revans2** [NVIDIA/spark-rapids#71] opened 2020-05-29 18:23 UTC
**Is your feature request related to a problem? Please describe.**
The `current_date` and `current_timestamp` functions are foldable leaf nodes and should just work, but it would be good to have tests to verify that they do and continue to work.

**Comment by sameerz** [comment] 2021-08-03 18:47
This is a duplicate of issue #27

**Closed** 2021-08-03 18:47 UTC
Labels: SQL, duplicate, feature request, test
