### ISSUE TITLE
[BUG] fastparquet tests fail on Databricks 13.3 due to NaNs becoming nulls when converting from pandas

### ISSUE THREAD

**Issue by jlowe** [NVIDIA/spark-rapids#9778] opened 2023-11-17 18:24 UTC
On Databricks 13.3, nulls in the Pandas DataFrame (represented as NaNs) are being honored as nulls in the resulting Spark DataFrame when converting a Pandas DataFrame to a Spark DataFrame.  Pandas thinks there are nulls in the data, and those nulls are propagating to the Spark DataFrame.

fastparquet loads the NaNs properly, but then when converting the data to pandas, pandas thinks the NaN values are null.  This, in turn, causes spark.createDataFrame to produce corresponding nulls.  When comparing this to the GPU direct load of the data that contains NaNs (not nulls), the test fails.  The problem is not in the way the GPU loads the data, it's the way the NaNs get converted into nulls due to sending the data through pandas before converting to a Spark DataFrame.

**Comment by sameerz** [comment] 2023-11-21 21:57
Duplicate of https://github.com/NVIDIA/spark-rapids/issues/9776

**Comment by mythrocks** [comment] 2023-11-21 22:52
This is a dupe of #9767.  I can address the fix there.

**Closed by mythrocks** 2023-11-21 22:52 UTC
Labels: bug, duplicate, test
