### ISSUE TITLE
[FEA] Audit 3.2.0 - [SPARK-34897][SQL] Support reconcile schemas based on index after nested column pruning

### ISSUE THREAD

**Issue by andygrove** [NVIDIA/spark-rapids#2780] opened 2021-06-22 17:50 UTC
**Is your feature request related to a problem? Please describe.**
I'm not sure if we need to do anything for this change in Spark but I think it needs further investigation just to be sure.

https://github.com/apache/spark/commit/e609395913

**Comment by sameerz** [comment] 2021-06-22 20:18
Duplicate of issue #463

**Closed** 2021-06-22 20:19 UTC
Labels: duplicate
