### ISSUE TITLE
[BUG] The buildall script is unable to create a multi-buildver jar when no parameters are passed

### ISSUE THREAD

**Issue by razajafri** [NVIDIA/spark-rapids#11514] opened 2024-09-26 23:59 UTC
The `buildall` script is broken when building all Spark versions without passing a parameter. 

```
spark-rapids-root> build/buildall 
spark-rapids-root> TESTS=parquet_test.py SPARK_HOME=~/spark-homes/spark-3.5.0-bin-hadoop3 integration_tests/run_pyspark_from_build.sh

```
The above command fails stating that the version 3.5.0 isn't supported when in fact it is.

**Comment by gerashegalov** [comment] 2024-09-27 05:15
dupe of #11509

**Closed** 2024-09-27 05:17 UTC
Labels: bug, ? - Needs Triage
