### ISSUE TITLE
[FEA] it will be nice if we support parse_url function

### ISSUE THREAD

**Issue by nvliyuan** [NVIDIA/spark-rapids#7899] opened 2023-03-20 10:24 UTC
I wish we can support parse_url function:

```
from pyspark.sql.types import StructType, StructField, StringType
spark = SparkSession.builder.enableHiveSupport().getOrCreate()
schema = StructType([
    StructField('id', StringType(), True),
    StructField('url', StringType(), True)
])

data = [('1', 'https://www.aaa.com/path1?param1=value1&param2=value2'),
        ('2', 'https://www.aaa.org/path2?param3=value3&param4=value4'),
        ('3', 'https://www.aaa.net/path3?param5=value5&param6=value6')]
df = spark.createDataFrame(data=data, schema=schema)
df.createOrReplaceTempView("my_table")
result = spark.sql("""
  SELECT
    id,
    parse_url(url, 'HOST') AS host,
    parse_url(url, 'PATH') AS path,
    parse_url(url, 'QUERY') AS query_params
  FROM my_table
""")
result.show()
```
![image](https://user-images.githubusercontent.com/84758614/226312316-ec4a229d-7e42-480b-859e-09bf5cdfd07b.png)

**Comment by sameerz** [comment] 2023-03-20 22:07
Duplicate of https://github.com/NVIDIA/spark-rapids/issues/6969

**Closed** 2023-03-21 22:06 UTC
Labels: duplicate, feature request
