### ISSUE TITLE
[TASK] Test Parquet reader for widening type promotions from INT to DECIMAL

### ISSUE THREAD

**Issue by mythrocks** [NVIDIA/spark-rapids#10576] opened 2024-03-12 22:45 UTC
This is related to [SPARK-40876](https://issues.apache.org/jira/browse/SPARK-40876).

For datasets that contain mixed types for the same column, across different input files, the non-vectorized Parquet reader in Apache Spark 3.x is capable of promoting to the wider type, if(f) it accommodates the input without losing precision.

For instance, consider that a single data directory contains 2 files, both containing column `col`.
1. `part-00000` has `INT32` `col`
2. `part-00001` has `DECIMAL(12,0)` `col`

Consider that the directory is being read as `col DECIMAL(12,0)`.

Apache Spark's non-vectorized Parquet reader automatically casts/promotes `part-00000`'s column to `DECIMAL(12,0)`.  After [SPARK-40876](https://issues.apache.org/jira/browse/SPARK-40876), this is also supported in the vectorized reader.

It would be good to verify that the tests from [this commit in Apache Spark](https://github.com/apache/spark/commit/0356ac00947) produce the same results on the Spark RAPIDS plugin (and CUDF).
The example mentioned in the commit is simply:
```scala
  Seq(20).toDF($"a".cast(IntegerType)).write.parquet(path)
  spark.read.schema("a decimal(12, 0)").parquet(path).collect()
```

Data munging of this sort might be a grey area, but it's common enough that past data might be reinstated or appended to.  This test might well be warranted.

**Comment by jlowe** [comment] 2024-03-13 13:38
Duplicate of #10558.

**Closed by jlowe** 2024-03-13 13:38 UTC
Labels: ? - Needs Triage, task, audit_4.0.0
