### ISSUE TITLE
[FEATURE] Spark 3.1 orc nested predicate pushdown support

### ISSUE THREAD

**Issue by tgravescs** [NVIDIA/spark-rapids#576] opened 2020-08-18 14:44 UTC
**Describe the bug**
Spark 3.1 added nested predicate pushdown support in ORC - https://github.com/apache/spark/commit/7b6e1d5cec60dbb43c6fbc1528a207cbff604a5d

This removed a function we were using:
E                   Caused by: java.lang.NoSuchMethodError: org.apache.spark.sql.execution.datasources.orc.OrcFiltersBase.isSearchableType$(Lorg/apache/spark/sql/execution/datasources/orc/OrcFiltersBase;Lorg/apache/spark/sql/types/DataType;)Z

We should go through and add the same support or fix it to use the new function.

**Steps/Code to reproduce bug**
Run spark 3.1.0 integration tests:
FAILED integration_tests/src/main/python/orc_test.py::test_input_meta - py4j....

**Expected behavior**
tests pass

**Environment details (please complete the following information)**
 - Environment location: [Standalone, YARN, Kubernetes, Cloud(specify cloud provider)]
 - Spark configuration settings related to the issue

**Additional context**

**Comment by tgravescs** [comment] 2020-08-31 14:46
this got backported to 3.0.1 so we need to fix for 0.2 release

**Comment by tgravescs** [comment] 2020-08-31 15:33
it looks like changes in 3.0.1 and 3.1.0 are also different so we would need a shim layer. Temporarily I'm going to put in a change to just copy the function that got moved to private:

  - protected[sql] def isSearchableType(dataType: DataType) = dataType match {
  + private def isSearchableType(dataType: DataType) = dataType match {

And then we can look at this in more detail to support it fully.

**Comment by tgravescs** [comment] 2021-02-09 23:38
ok so leaving a P2 because we fixed the function and it works, this is only needed if we want to support nested predicate pushdown

**Comment by sameerz** [comment] 2021-04-20 21:06
Depends on https://github.com/rapidsai/cudf/issues/7640 and https://github.com/rapidsai/cudf/issues/7830

**Comment by tgravescs** [comment] 2021-07-14 13:09
our orc filter code was updated with https://github.com/NVIDIA/spark-rapids/pull/1982 and it looks like this should just work, so perhaps we just need to test it.

**Comment by jlowe** [comment] 2021-07-20 21:29
Closing as a duplicate of #463

**Closed by jlowe** 2021-07-20 21:29 UTC
Labels: P1, Spark 3.1+, cudf_dependency, feature request
