### ISSUE TITLE
[BUG] test_hash_groupby_approx_percentile_long_repeated_keys could hang in integration tests intermittently

### ISSUE THREAD

**Issue by pxLi** [NVIDIA/spark-rapids#3692] opened 2021-09-29 00:40 UTC
**Describe the bug**
hash_aggregate_test of some integration tests failed intermittently due to timeout for spark standalone or databricks 
e.g. 
rapids_databricks_nightly-dev-github/161 db 7.3 runtime, plugin 21.12
rapids_integration-dev-github/297/ spark 3.0.2, plugin 21.12
rapids_it-3.0.2-AQE-dev-github/287/ plugin 21.12
rapids_integration-pre_release-github/371 spark 3.1.2, plugin 21.10

Those are not always reproducible
it looks like to be related to https://github.com/NVIDIA/spark-rapids/pull/3301/

checked log all above builds were hanging at
../../src/main/python/hash_aggregate_test.py::test_hash_groupby_approx_percentile_long_repeated_keys[IGNORE_ORDER({'local': True})] 

executor log was just hung there w/o any further output
```
21/09/28 21:33:08 INFO Executor: Running task 11.0 in stage 6859.0 (TID 39872)
21/09/28 21:33:08 INFO ShuffleBlockFetcherIterator: Getting 2 (414.0 B) non-empty blocks including 2 (414.0 B) local and 0 (0.0 B) host-local and 0 (0.0 B) remote blocks
21/09/28 21:33:08 INFO ShuffleBlockFetcherIterator: Started 0 remote fetches in 0 ms
21/09/28 21:33:08 INFO Executor: Finished task 11.0 in stage 6859.0 (TID 39872). 5071 bytes result sent to driver
21/09/28 21:33:08 INFO CoarseGrainedExecutorBackend: Got assigned task 39873
21/09/28 21:33:08 INFO Executor: Running task 4.0 in stage 6859.0 (TID 39873)
21/09/28 21:33:08 INFO ShuffleBlockFetcherIterator: Getting 0 (0.0 B) non-empty blocks including 0 (0.0 B) local and 0 (0.0 B) host-local and 0 (0.0 B) remote blocks
21/09/28 21:33:08 INFO ShuffleBlockFetcherIterator: Started 0 remote fetches in 0 ms
21/09/28 21:33:08 INFO Executor: Finished task 4.0 in stage 6859.0 (TID 39873). 4925 bytes result sent to driver
21/09/28 21:33:08 INFO CoarseGrainedExecutorBackend: Got assigned task 39874
21/09/28 21:33:08 INFO Executor: Running task 6.0 in stage 6859.0 (TID 39874)
21/09/28 21:33:08 INFO ShuffleBlockFetcherIterator: Getting 0 (0.0 B) non-empty blocks including 0 (0.0 B) local and 0 (0.0 B) host-local and 0 (0.0 B) remote blocks
21/09/28 21:33:08 INFO ShuffleBlockFetcherIterator: Started 0 remote fetches in 0 ms
21/09/28 21:33:08 INFO Executor: Finished task 6.0 in stage 6859.0 (TID 39874). 4968 bytes result sent to driver
21/09/28 21:33:08 INFO CoarseGrainedExecutorBackend: Got assigned task 39875
21/09/28 21:33:08 INFO Executor: Running task 8.0 in stage 6859.0 (TID 39875)
21/09/28 21:33:08 INFO ShuffleBlockFetcherIterator: Getting 0 (0.0 B) non-empty blocks including 0 (0.0 B) local and 0 (0.0 B) host-local and 0 (0.0 B) remote blocks
21/09/28 21:33:08 INFO ShuffleBlockFetcherIterator: Started 0 remote fetches in 0 ms
21/09/28 21:33:08 INFO Executor: Finished task 8.0 in stage 6859.0 (TID 39875). 4968 bytes result sent to driver
```

**Comment by pxLi** [comment] 2021-09-29 00:49
another intermittent error saw in 21.10 spark 3.1.1

```
[2021-09-28T21:34:02.411Z] =================================== FAILURES ===================================

[2021-09-28T21:34:02.411Z] ____________ test_hash_groupby_approx_percentile_long_repeated_keys ____________

[2021-09-28T21:34:02.412Z] 

[2021-09-28T21:34:02.412Z]     @ignore_order(local=True)

[2021-09-28T21:34:02.412Z]     def test_hash_groupby_approx_percentile_long_repeated_keys():

[2021-09-28T21:34:02.412Z] >       compare_percentile_approx(

[2021-09-28T21:34:02.412Z]             lambda spark: gen_df(spark, [('k', RepeatSeqGen(LongGen(), length=20)),

[2021-09-28T21:34:02.412Z]                                          ('v', LongRangeGen())], length=100),

[2021-09-28T21:34:02.412Z]             [0.05, 0.25, 0.5, 0.75, 0.95])

[2021-09-28T21:34:02.412Z] 

[2021-09-28T21:34:02.412Z] ../../src/main/python/hash_aggregate_test.py:1081: 

[2021-09-28T21:34:02.412Z] _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

[2021-09-28T21:34:02.412Z] 

[2021-09-28T21:34:02.412Z] df_fun = <function test_hash_groupby_approx_percentile_long_repeated_keys.<locals>.<lambda> at 0x7f278837b310>

[2021-09-28T21:34:02.412Z] percentiles = [0.05, 0.25, 0.5, 0.75, 0.95]

[2021-09-28T21:34:02.412Z] 

[2021-09-28T21:34:02.412Z]     def compare_percentile_approx(df_fun, percentiles):

[2021-09-28T21:34:02.412Z]     

[2021-09-28T21:34:02.412Z]         # create SQL statements for exact and approx percentiles

[2021-09-28T21:34:02.412Z]         p_exact_sql = create_percentile_sql("percentile", percentiles)

[2021-09-28T21:34:02.412Z]         p_approx_sql = create_percentile_sql("approx_percentile", percentiles)

[2021-09-28T21:34:02.412Z]     

[2021-09-28T21:34:02.412Z]         def run_exact(spark):

[2021-09-28T21:34:02.412Z]             df = df_fun(spark)

[2021-09-28T21:34:02.412Z]             df.createOrReplaceTempView("t")

[2021-09-28T21:34:02.412Z]             return spark.sql(p_exact_sql)

[2021-09-28T21:34:02.412Z]     

[2021-09-28T21:34:02.412Z]         def run_approx(spark):

[2021-09-28T21:34:02.412Z]             df = df_fun(spark)

[2021-09-28T21:34:02.412Z]             df.createOrReplaceTempView("t")

[2021-09-28T21:34:02.412Z]             return spark.sql(p_approx_sql)

[2021-09-28T21:34:02.412Z]     

[2021-09-28T21:34:02.412Z]         # run exact percentile on CPU

[2021-09-28T21:34:02.412Z]         exact = run_with_cpu(run_exact, 'COLLECT', _approx_percentile_conf)

[2021-09-28T21:34:02.412Z]     

[2021-09-28T21:34:02.412Z]         # run approx_percentile on CPU and GPU

[2021-09-28T21:34:02.412Z]         approx_cpu, approx_gpu = run_with_cpu_and_gpu(run_approx, 'COLLECT', _approx_percentile_conf)

[2021-09-28T21:34:02.412Z]     

[2021-09-28T21:34:02.412Z]         for result in zip(exact, approx_cpu, approx_gpu):

[2021-09-28T21:34:02.412Z]             # assert that keys match

[2021-09-28T21:34:02.412Z]             assert result[0]['k'] == result[1]['k']

[2021-09-28T21:34:02.412Z]             assert result[1]['k'] == result[2]['k']

[2021-09-28T21:34:02.412Z]     

[2021-09-28T21:34:02.412Z]             exact = result[0]['the_percentile']

[2021-09-28T21:34:02.412Z]             cpu = result[1]['the_percentile']

[2021-09-28T21:34:02.412Z]             gpu = result[2]['the_percentile']

[2021-09-28T21:34:02.412Z]     

[2021-09-28T21:34:02.412Z]             if exact is not None:

[2021-09-28T21:34:02.412Z]                 if isinstance(exact, list):

[2021-09-28T21:34:02.412Z] >                   for x in zip(exact, cpu, gpu):

[2021-09-28T21:34:02.412Z] E                   TypeError: 'NoneType' object is not iterable

[2021-09-28T21:34:02.412Z] 

[2021-09-28T21:34:02.412Z] ../../src/main/python/hash_aggregate_test.py:1151: TypeError
```

**Comment by tgravescs** [comment] 2021-09-29 12:44
not sure but also seeing https://github.com/NVIDIA/spark-rapids/issues/3697 with hash aggregate tests

**Comment by abellina** [comment] 2021-09-29 16:19
Another report: https://github.com/NVIDIA/spark-rapids/issues/3703

**Comment by sameerz** [comment] 2021-10-05 21:07
Duplicate of #3703

**Closed by sameerz** 2021-10-05 21:07 UTC
Labels: bug, ? - Needs Triage, P1
