### ISSUE TITLE
[FEA] Support reverse

### ISSUE THREAD

**Issue by viadea** [NVIDIA/spark-rapids#6885] opened 2022-10-21 18:17 UTC
I wish we can support reverse function.
```
select reverse(a) from test_diff_schema_evo;
    ! <Reverse> reverse(a#0) cannot run on GPU because GPU does not currently support the operator class org.apache.spark.sql.catalyst.expressions.Reverse
```

**Comment by revans2** [comment] 2022-11-02 14:42
I don't see any existing cudf functionality that will do what we want. @viadea do you want revers for string, array, or both?

We will need separate kernels or APIs for each of these. This is because just reversing the bits in a UTF-8 string will not reverse the string because strings are multi-byte.

**Comment by viadea** [comment] 2022-11-09 17:34
@revans2  String is good for now. i can show you a real example offline

**Comment by ttnghia** [comment] 2022-11-18 19:50
In cudf string is just a special case of array: array of char. So we can support both at the same time.

**Comment by ttnghia** [comment] 2022-11-18 19:54
Some example:
```
scala> val df = Seq("this is a string", "another test string").toDF("s")
df: org.apache.spark.sql.DataFrame = [s: string]

scala> df.show
+-------------------+
|                  s|
+-------------------+
|   this is a string|
|another test string|
+-------------------+


scala> df.selectExpr("reverse(s)").show
+-------------------+
|         reverse(s)|
+-------------------+
|   gnirts a si siht|
|gnirts tset rehtona|
+-------------------+


scala> val df2 = Seq(Seq(1, 2, 3), Seq(4, 5, 6)).toDF("i")
df2: org.apache.spark.sql.DataFrame = [i: array<int>]

scala> df2.show
+---------+
|        i|
+---------+
|[1, 2, 3]|
|[4, 5, 6]|
+---------+


scala> df2.selectExpr("reverse(i)").show
+----------+
|reverse(i)|
+----------+
| [3, 2, 1]|
| [6, 5, 4]|
+----------+

```

**Comment by ttnghia** [comment] 2022-11-18 19:55
I was worried if `reverse("this is a string")` could produce `"string a is this"` but it didn't, which is very good.

**Comment by ttnghia** [comment] 2022-11-18 21:02
I think this can be done entirely in the plugin, using gather map + `cudf::sequence`.

**Comment by revans2** [comment] 2022-11-18 21:20
The problem is that strings are stored in UTF-8, which supports multi-byte characters. ASCII we can probably do it very simply, but for anything that is not ASCII it will potentially corrupt the string.

**Comment by ttnghia** [comment] 2022-11-18 21:31
I see-so the same implementation can't be used for both, but the implementation should be very similar and straightforward.

**Comment by revans2** [comment] 2022-11-18 22:19
For a list reverse a gather map would likely work well. It would be even better if you could not have to materialize the gather map, because for some list types the gather map is going to be larger than the list column itself. But that is probably a minor optimization.

If you look at https://github.com/rapidsai/cudf/blob/branch-23.02/cpp/include/cudf/strings/detail/utf8.hpp it provides APIs to be able to see if the current byte is part of a multi-byte character or not, and what the length of it is. If you can find a good way to do this type of thing in parallel, then great. But from what I have seen most of the string APIs work by having a single thread per string. Even then we might be able to play some games to coalesce reads and writes to speed things up.

**Comment by ttnghia** [comment] 2022-11-30 21:23
We also have a duplicate issue: https://github.com/NVIDIA/spark-rapids/issues/4375

**Comment by sameerz** [comment] 2022-12-02 14:43
Also depends on https://github.com/rapidsai/cudf/pull/12283

**Comment by ttnghia** [comment] 2022-12-14 00:24
The libcudf PR for array input type was merged. We can continue to complete our plugin work.

**Closed** 2022-12-19 17:13 UTC
Labels: feature request, cudf_dependency
