### ISSUE TITLE
[FEA] Improve CollectLimitExec's performance

### ISSUE THREAD

**Issue by razajafri** [NVIDIA/spark-rapids#1623] opened 2021-01-29 05:14 UTC
The CollectLimitExec was turned off by default because it would not ramp up in how it did collect. It would be great to be able to turn it on so we could avoid moving extra data between the GPU and the CPU when doing a common operation that shows up regularly in operations like `show`.

The reason why it was turned off was because replacing CollectLimitExec the way it was done was causing us to process all partitions in some cases where as the CPU side is able to just run it on a single partition. More details can be found in issue #900

**Comment by tgravescs** [comment] 2021-01-29 14:38
so it would be nice to have more description here.  
- ie reason/link to why it was turned off. -> https://github.com/NVIDIA/spark-rapids/pull/900
- why do we want/need to turn it back on

**Comment by revans2** [comment] 2021-01-29 14:48
The issue is that we are changing CollectLimitExec into a LocalLimit followed by a shuffle to a single executor and then a GlobalLimit.  

https://github.com/NVIDIA/spark-rapids/blob/f28ec637ab5205dff9ed2560cc503722611eb850/sql-plugin/src/main/scala/com/nvidia/spark/rapids/limit.scala#L139-L142

This technically works, but requires all of the tasks that are a part of the LocalLimit to run, shuffle data,...  Spark takes a different approach and has a special function in SparkPlan that allows for a fast path in collect called `executeCollect`.

https://github.com/apache/spark/blob/588ddcdf22fccec2ea3775d17ac3d19cd5328eb5/sql/core/src/main/scala/org/apache/spark/sql/execution/limit.scala#L47

This returns an `Array[InternalRow]` instead of an RDD.  

So we need to implement a `GpuCollectLimitExec` that will do the equivalent of local limit, shuffle to a single executor, global limit. But there are a few gotchas here with the shuffle so be careful with it.

Now things start to get kind of complicated. We want to be able to implement an `executeCollect` method, but it is never going to be called without some changes to how our plan works.  Right now if a `SparkPlan` implementation supports columnar, then a transition to rows will be inserted automatically and none of the row based APIs will ever be called. We need to tag our GpuCollectLimitExec so when we post process the plan we know that it too can produce row based output so we don't need to insert in a transition. (NOTE this is something that would help a lot with #932 too).

After that then you need to implement in `GpuCollectLimit` all of the APIs to let it output rows too.  Which means we would likely need to run the columnar version and then transition the data back to rows.

Finally at this point you can implement a custom `executeCollect`. This also is not going to be simple because the Spark version relies on a special `executeTake` method that will not work out of the box for out GpuExec instances.  We likely will have to implement something new that does the same kind of thing for them.

**Comment by revans2** [comment] 2021-01-29 14:53
>     * why do we want/need to turn it back on?

Why didn't we just delete the implementation in #900 and mark CollectLimitExec as something we would never do? We want to turn it back on so that ideally it is more performant, and from a marketing perspective being able to say that the entire query is on the GPU is great.

Is it worth the effort to do that at this time?  That I am less sure about.

**Comment by jlowe** [comment] 2024-02-14 19:01
We currently do not replace CollectLimitExec by default and have no plans to change this.

**Closed by jlowe** 2024-02-14 19:01 UTC
Labels: feature request, performance
