### ISSUE TITLE
[FEA] Add support for round-robin partitioning for ArrayType(StringType,false)

### ISSUE THREAD

**Issue by viadea** [NVIDIA/spark-rapids#8686] opened 2023-07-11 01:02 UTC
I wish we can add  support for round-robin partitioning for ArrayType(StringType,false) when `spark.sql.execution.sortBeforeRepartition=true`. 
This is because currently GPU Sort does support ArrayType(StringType,false).

And in the meantime, we should let the Sort fallback to replace the "round-robin partitioning" fallback.

Below is an example not-supported message:
```
!Exec <ShuffleExchangeExec> cannot run on GPU because round-robin partitioning cannot sort ArrayType(StringType,false) to run this on the GPU set spark.sql.execution.sortBeforeRepartition to false
```

**Comment by jlowe** [comment] 2023-07-11 14:30
This is probably a duplicate of #7807.

**Closed** 2023-07-18 20:08 UTC
Labels: duplicate, feature request
