### ISSUE TITLE
[BUG] ConcurrentModificationException error after scala test suite completes

### ISSUE THREAD

**Issue by andygrove** [NVIDIA/spark-rapids#1140] opened 2020-11-17 15:48 UTC
**Describe the bug**
I've noticed this error a few times lately after the Scala test suite completes.

```
Exception in thread "Thread-7" java.util.ConcurrentModificationException
	at java.util.LinkedList$LLSpliterator.forEachRemaining(LinkedList.java:1239)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:566)
	at ai.rapids.cudf.MemoryCleaner.stringJoin(MemoryCleaner.java:271)
	at ai.rapids.cudf.MemoryCleaner.access$200(MemoryCleaner.java:59)
	at ai.rapids.cudf.MemoryCleaner$Cleaner.logRefCountDebug(MemoryCleaner.java:94)
	at ai.rapids.cudf.ColumnVector$OffHeapState.cleanImpl(ColumnVector.java:3468)
	at ai.rapids.cudf.MemoryCleaner$Cleaner.clean(MemoryCleaner.java:104)
	at ai.rapids.cudf.MemoryCleaner$CleanerWeakReference.clean(MemoryCleaner.java:150)
	at ai.rapids.cudf.MemoryCleaner.lambda$static$1(MemoryCleaner.java:213)
	at java.lang.Thread.run(Thread.java:748)
```

**Steps/Code to reproduce bug**
`mvn clean verify`

**Expected behavior**
We should not see this error.

**Environment details (please complete the following information)**
Running on Ubuntu desktop

**Additional context**
N/A

**Comment by abellina** [comment] 2020-11-17 15:49
This one is a duplicate of https://github.com/NVIDIA/spark-rapids/issues/1128

**Closed** 2020-11-17 15:56 UTC
Labels: ? - Needs Triage, bug
