### ISSUE TITLE
[FEA] [Audit] [SPARK-38086][SQL] - Investigate if  ArrowColumnVector needs to made Extendable

### ISSUE THREAD

**Issue by nartal1** [NVIDIA/spark-rapids#4867] opened 2022-02-24 23:48 UTC
**Is your feature request related to a problem? Please describe.**
Spark has made ArrowColumnVector as extendable in the below PR. We have copied some of the code in AccessibleArrowColumnVector.java . So need to investigate if this PR is to be pulled in.

Spark PR: https://github.com/apache/spark/commit/de5e45ab5d

**Comment by sameerz** [comment] 2022-03-01 21:18
This is a duplicate of https://github.com/NVIDIA/spark-rapids/issues/4689

**Closed by sameerz** 2022-03-01 21:18 UTC
Labels: duplicate, audit_3.3.0
