### ISSUE TITLE
[BUG] A DEVICE COLUMN VECTOR WAS LEAKED 

### ISSUE THREAD

**Issue by mtsol** [NVIDIA/spark-rapids#6992] opened 2022-11-03 10:42 UTC
10:46:04.206 [Thread-7] INFO  com.nvidia.spark.rapids.GpuOverrides - Plan conversion to the GPU took 0.85 ms
10:46:04.206 [Thread-7] INFO  com.nvidia.spark.rapids.GpuOverrides - GPU plan transition optimization took 0.19 ms
10:46:04.804 [Cleaner Thread] ERROR ai.rapids.cudf.ColumnVector - A DEVICE COLUMN VECTOR WAS LEAKED (ID: 747852 7d22997dd7d0)
10:46:04.805 [Cleaner Thread] ERROR ai.rapids.cudf.ColumnVector - A DEVICE COLUMN VECTOR WAS LEAKED (ID: 747786 7f11785e7b50)
10:46:04.806 [dispatcher-BlockManagerMaster] INFO  org.apache.spark.storage.BlockManagerInfo - Removed broadcast_182_piece0 on smcpappprlv314101.i2cinc.local:39575 in memory (size: 292.7 KiB, free: 31.7 GiB)
10:46:04.806 [Cleaner Thread] ERROR ai.rapids.cudf.ColumnVector - A DEVICE COLUMN VECTOR WAS LEAKED (ID: 747779 7f1178582c50)

**Steps/Code to reproduce bug**
A lot of continuous transformations are performed on a spark dataframe in loop.

**Expected behavior**
should not leak

**Environment details (please complete the following information)**
 - Environment location: master local
 - Executor memory and driver memory each 60g 

**Additional context**
Rapids version used 22.06

**Comment by jlowe** [comment] 2022-11-03 14:48
Thanks for the report!  We're going to need more information to fix this issue.  Can you please do one of the following?
- Provide detailed instructions on how we can reproduce the issue
- Repeat the problem on your end with the Java system property `ai.rapids.refcount.debug` set to `true`.  For example, if running in a distributed cluster mode, set this property on the executors via the Spark option: `-Dspark.executor.extraJavaOptions="-Dai.rapids.refcount.debug=true"`. This will cause one or more stacktraces to be logged for each leak, and those stacktraces are what we need to help debug the cause of the leak.

**Comment by jlowe** [comment] 2022-11-08 21:10
@mtsol have you had a chance to look into this further?  We're going to need more information to make progress on this.

**Comment by sameerz** [comment] 2022-11-16 21:09
@mtsol, would you have a chance to provide more information on this issue?  You can also reach out to us at spark-rapids-support at nvidia dot com for help.

**Comment by sameerz** [comment] 2022-11-22 21:03
Hi @mstol, I am going to close this issue for now.  In case you are able to provide more information please add it here and reopen.  Thanks!

**Closed by sameerz** 2022-11-22 21:03 UTC
Labels: bug, ? - Needs Triage
