### ISSUE TITLE
[BUG] RegexpExtract OOM with large batch sizes

### ISSUE THREAD

**Issue by tgravescs** [NVIDIA/spark-rapids#7656] opened 2023-02-03 14:11 UTC
**Describe the bug**
Customer has a query where they are using regexp_extract in side of a join that becomes a BHJ.  If we run with the full batch size using 2 concurrent tasks this OOMs.  If you cut the batch size down to 256m it runs ok. 

The query looks like this:

```
inner join sometable on
	(foo =  case when id like '%-val-%' then regexp_extract(id, '(\\\\d+)-val-(\\\\d+)', 1) else val end
	and id2 = case when id like '%-val-%' then regexp_extract(id, '(\\\\d+)-val-(\\\\d+)', 2) else -1 end)
where
```

It would be nice if we can investigate a way to batch or something so we don't OOM and have to cut the batch size down since it hurt performance of other execs and queries in this same application.

**Comment by sameerz** [comment] 2023-02-07 21:48
Duplicate of https://github.com/NVIDIA/spark-rapids/issues/7640

**Closed by sameerz** 2023-02-07 21:48 UTC
Labels: bug, duplicate
