### ISSUE TITLE
Reconsider Parquet read buffer size

### ISSUE THREAD

**Issue by jlowe** [NVIDIA/spark-rapids#11162] opened 2024-07-09 21:33 UTC
ParquetPartitionReaderBase uses the parquet.read.allocation.size config to control the copy buffer used for reading from the Parquet input stream.  The default is 8MB which is pretty big, especially when there are many reader threads via the multithreaded reader.  With a large number of reader threads all performing Parquet reads, these per-thread buffers can add up to a nontrivial amount of heap memory which can trigger OOMs.  We should do some empirical measurements in various environments to see if we can significantly lower the default for this.

**Comment by sameerz** [comment] 2024-07-23 20:22
Duplicate of issue #9269

**Closed by sameerz** 2024-07-23 20:22 UTC
Labels: duplicate, reliability
