### ISSUE TITLE
[BUG] MultiFileCloudParquetPartitionReader can trigger NPE

### ISSUE THREAD

**Issue by jlowe** [NVIDIA/spark-rapids#2915] opened 2021-07-12 22:30 UTC
**Describe the bug**
One of the nightly pipelines that uses an S3 input recently crashed with the following exception:
```
17:22:13  Caused by: java.lang.NullPointerException
17:22:13  	at org.apache.hadoop.fs.s3a.S3AInputStream.lambda$read$3(S3AInputStream.java:450)
17:22:13  	at org.apache.hadoop.fs.s3a.Invoker.once(Invoker.java:109)
17:22:13  	at org.apache.hadoop.fs.s3a.Invoker.lambda$retry$3(Invoker.java:265)
17:22:13  	at org.apache.hadoop.fs.s3a.Invoker.retryUntranslated(Invoker.java:322)
17:22:13  	at org.apache.hadoop.fs.s3a.Invoker.retry(Invoker.java:261)
17:22:13  	at org.apache.hadoop.fs.s3a.Invoker.retry(Invoker.java:236)
17:22:13  	at org.apache.hadoop.fs.s3a.S3AInputStream.read(S3AInputStream.java:446)
17:22:13  	at java.io.DataInputStream.readFully(DataInputStream.java:195)
17:22:13  	at com.nvidia.spark.rapids.ParquetPartitionReaderBase.copyDataRange(GpuParquetScan.scala:509)
17:22:13  	at com.nvidia.spark.rapids.ParquetPartitionReaderBase.copyDataRange$(GpuParquetScan.scala:497)
17:22:13  	at com.nvidia.spark.rapids.MultiFileCloudParquetPartitionReader.copyDataRange(GpuParquetScan.scala:975)
17:22:13  	at com.nvidia.spark.rapids.ParquetPartitionReaderBase.$anonfun$copyBlocksData$3(GpuParquetScan.scala:580)
17:22:13  	at com.nvidia.spark.rapids.ParquetPartitionReaderBase.$anonfun$copyBlocksData$3$adapted(GpuParquetScan.scala:580)
17:22:13  	at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:62)
17:22:13  	at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:55)
17:22:13  	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:49)
17:22:13  	at com.nvidia.spark.rapids.ParquetPartitionReaderBase.copyBlocksData(GpuParquetScan.scala:580)
17:22:13  	at com.nvidia.spark.rapids.ParquetPartitionReaderBase.copyBlocksData$(GpuParquetScan.scala:525)
17:22:13  	at com.nvidia.spark.rapids.MultiFileCloudParquetPartitionReader.copyBlocksData(GpuParquetScan.scala:975)
17:22:13  	at com.nvidia.spark.rapids.ParquetPartitionReaderBase.$anonfun$readPartFile$3(GpuParquetScan.scala:669)
17:22:13  	at com.nvidia.spark.rapids.Arm.closeOnExcept(Arm.scala:87)
17:22:13  	at com.nvidia.spark.rapids.Arm.closeOnExcept$(Arm.scala:85)
17:22:13  	at com.nvidia.spark.rapids.FilePartitionReaderBase.closeOnExcept(GpuMultiFileReader.scala:236)
17:22:13  	at com.nvidia.spark.rapids.ParquetPartitionReaderBase.$anonfun$readPartFile$2(GpuParquetScan.scala:666)
17:22:13  	at com.nvidia.spark.rapids.Arm.withResource(Arm.scala:28)
17:22:13  	at com.nvidia.spark.rapids.Arm.withResource$(Arm.scala:26)
17:22:13  	at com.nvidia.spark.rapids.FilePartitionReaderBase.withResource(GpuMultiFileReader.scala:236)
17:22:13  	at com.nvidia.spark.rapids.ParquetPartitionReaderBase.$anonfun$readPartFile$1(GpuParquetScan.scala:664)
17:22:13  	at com.nvidia.spark.rapids.Arm.withResource(Arm.scala:28)
17:22:13  	at com.nvidia.spark.rapids.Arm.withResource$(Arm.scala:26)
17:22:13  	at com.nvidia.spark.rapids.FilePartitionReaderBase.withResource(GpuMultiFileReader.scala:236)
17:22:13  	at com.nvidia.spark.rapids.ParquetPartitionReaderBase.readPartFile(GpuParquetScan.scala:663)
17:22:13  	at com.nvidia.spark.rapids.ParquetPartitionReaderBase.readPartFile$(GpuParquetScan.scala:658)
17:22:13  	at com.nvidia.spark.rapids.MultiFileCloudParquetPartitionReader.readPartFile(GpuParquetScan.scala:975)
17:22:13  	at com.nvidia.spark.rapids.MultiFileCloudParquetPartitionReader$ReadBatchRunner.call(GpuParquetScan.scala:1043)
17:22:13  	at com.nvidia.spark.rapids.MultiFileCloudParquetPartitionReader$ReadBatchRunner.call(GpuParquetScan.scala:999)
17:22:13  	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
17:22:13  	... 3 more
```

**Comment by GaryShen2008** [comment] 2021-07-13 01:25
It may be impacted by the service down of internal s3. Assign to Bobby W first. Let's check it after the service is back.

**Comment by jlowe** [comment] 2021-07-13 13:58
> Let's check it after the service is back.

I disagree. This is an NPE.  Software should *never* throw an NPE to the user.  We need to walk the stacktrace to determine what was null to cause the NPE to be thrown and whether our software triggered the null dereference in the S3 client (e.g.: by passing null buffers, trying to use the connection after it was closed, etc.).  If the NPE was solely a problem in the S3 client then there's not much for us to do other than recommend users upgrade if they are hit by this condition, but if our software triggered it indirectly then we need to fix it.  Waiting for the S3 service to be restored and seeing it work afterwards does not necessarily mean a bug doesn't exist in our software.

**Comment by GaryShen2008** [comment] 2021-07-13 23:30
> 
> 
> > Let's check it after the service is back.
> 
> I disagree. This is an NPE. Software should _never_ throw an NPE to the user. We need to walk the stacktrace to determine what was null to cause the NPE to be thrown and whether our software triggered the null dereference in the S3 client (e.g.: by passing null buffers, trying to use the connection after it was closed, etc.). If the NPE was solely a problem in the S3 client then there's not much for us to do other than recommend users upgrade if they are hit by this condition, but if our software triggered it indirectly then we need to fix it. Waiting for the S3 service to be restored and seeing it work afterwards does not necessarily mean a bug doesn't exist in our software.

Got it. @wbo4958 Can you check the call stack and figure out where caused the NPE?

**Comment by wbo4958** [comment] 2021-07-16 09:09
From the exception stack and the code,

It seems the [wrappedStream](https://github.com/apache/hadoop/blob/branch-3.2.0/hadoop-tools/hadoop-aws/src/main/java/org/apache/hadoop/fs/s3a/S3AInputStream.java#L450,) is null. Looks like when one thread is trying to read, the other thread has closed the Stream. 

But the DEBUG log is not enabled, I can't find any suspicious log.

BTW,  When this issue happened, our swiftstack is unstable. And the issue is gone when swiftstack is stable. 

@tgravescs Would you help to look at this issue?

**Comment by tgravescs** [comment] 2021-07-16 13:44
so taking a look it would have had to have closeStream called on it. The S3AInputStream does have a OnReadFailure.reopen call which would close it and attempt to create new one.  This is called from the retry logic there.
It does seem like on the reopen call that they check to make sure the wrappedStream came back as non-null:
https://github.com/apache/hadoop/blob/f6c4e006cd1190e27fadbe0a38ce09782f45ca04/hadoop-tools/hadoop-aws/src/main/java/org/apache/hadoop/fs/s3a/S3AInputStream.java#L186

If that line number is right though it wasn't in the reopen case so perhaps it just got closeStream called on it by someone else.

We open the file in a single thread, its not shared across threads so it shouldn't be our code closing during read.

I think we'd have to rebuild it with some debugging to see for sure.

**Comment by wbo4958** [comment] 2021-07-19 13:42
I tried to repro this issue locally by breaking the network connection but failed to repro. :(

**Comment by wbo4958** [comment] 2021-07-21 11:13
I found Hadoop-aws may have  a corner case can result in the NPE issue,

Before NPE happened, there were other exceptions happened, see below 

```
21/07/12 22:19:17 INFO S3AInputStream: Got exception while trying to read from stream XXX trying to recover: javax.net.ssl.SSLException: Read timed out
```
when [reading from S3 storage](https://github.com/apache/hadoop/blob/rel/release-3.2.0/hadoop-tools/hadoop-aws/src/main/java/org/apache/hadoop/fs/s3a/S3AInputStream.java#L450), SSLException (which extends IOException) happens, which will trigger [onReadFailure](https://github.com/apache/hadoop/blob/rel/release-3.2.0/hadoop-tools/hadoop-aws/src/main/java/org/apache/hadoop/fs/s3a/S3AInputStream.java#L458). 

onReadFailure calls reopen. it will first close the original **wrappedStream** and set **wrappedStream = null**, and then it will try to [re-get **wrappedStream**](https://github.com/apache/hadoop/blob/rel/release-3.2.0/hadoop-tools/hadoop-aws/src/main/java/org/apache/hadoop/fs/s3a/S3AInputStream.java#L184).  But what if the previous code [obtaining S3Object](https://github.com/apache/hadoop/blob/rel/release-3.2.0/hadoop-tools/hadoop-aws/src/main/java/org/apache/hadoop/fs/s3a/S3AInputStream.java#L183) throw exception, then "wrappedStream" will be null.

And the [retry](https://github.com/apache/hadoop/blob/rel/release-3.2.0/hadoop-tools/hadoop-aws/src/main/java/org/apache/hadoop/fs/s3a/S3AInputStream.java#L446) mechanism may re-execute the [wrappedStream.read](https://github.com/apache/hadoop/blob/rel/release-3.2.0/hadoop-tools/hadoop-aws/src/main/java/org/apache/hadoop/fs/s3a/S3AInputStream.java#L450) and cause NPE.

I will try to verify my guess by hacking some code.

**Comment by GaryShen2008** [comment] 2021-07-21 13:45
Good progress. From the code, it seems possible. If we can understand the [retryPolicy](https://github.com/apache/hadoop/blob/rel/release-3.2.0/hadoop-tools/hadoop-aws/src/main/java/org/apache/hadoop/fs/s3a/Invoker.java#L340), it'll help.
If so, I think it should be a bug in hadoop aws.

**Comment by wbo4958** [comment] 2021-07-21 23:48
``` patch
diff --git a/hadoop-tools/hadoop-aws/src/main/java/org/apache/hadoop/fs/s3a/S3AInputStream.java b/hadoop-tools/hadoop-aws/src/main/java/org/apache/hadoop/fs/s3a/S3AInputStream.java
index 68f98e4abea..d615d9a5c95 100644
--- a/hadoop-tools/hadoop-aws/src/main/java/org/apache/hadoop/fs/s3a/S3AInputStream.java
+++ b/hadoop-tools/hadoop-aws/src/main/java/org/apache/hadoop/fs/s3a/S3AInputStream.java
@@ -157,7 +157,7 @@ private void setInputPolicy(S3AInputPolicy inputPolicy) {
    */
   @Retries.OnceTranslated
   private synchronized void reopen(String reason, long targetPos, long length,
-          boolean forceAbort) throws IOException {
+          boolean forceAbort, boolean hack) throws IOException {
 
     if (wrappedStream != null) {
       closeStream("reopen(" + reason + ")", contentRangeFinish, forceAbort);
@@ -181,6 +181,9 @@ private synchronized void reopen(String reason, long targetPos, long length,
         (opencount == 0 ? "open" : "re-open"), uri, targetPos);
     S3Object object = context.getReadInvoker().once(text, uri,
         () -> client.getObject(request));
+    if (hack) {
+      throw new IOException("reopen hack");
+    }
     wrappedStream = object.getObjectContent();
     contentRangeStart = targetPos;
     if (wrappedStream == null) {
@@ -325,7 +328,7 @@ private void lazySeek(long targetPos, long len) throws IOException {
 
           //re-open at specific location if needed
           if (wrappedStream == null) {
-            reopen("read from new offset", targetPos, len, false);
+            reopen("read from new offset", targetPos, len, false, false);
           }
         });
   }
@@ -403,7 +406,7 @@ private void onReadFailure(IOException ioe, int length, boolean forceAbort)
     LOG.info("Got exception while trying to read from stream {}" +
         " trying to recover: " + ioe, uri);
     streamStatistics.readException();
-    reopen("failure recovery", pos, length, forceAbort);
+    reopen("failure recovery", pos, length, forceAbort, true);
   }
 
   /**
@@ -448,6 +451,9 @@ public synchronized int read(byte[] buf, int off, int len)
           int bytes;
           try {
             bytes = wrappedStream.read(buf, off, len);
+            if (bytes >= -10000) {
+              throw new IOException("Hacked --- ");
+            }
           } catch (EOFException e) {
             // the base implementation swallows EOFs.
             return -1;
```

After applying the patch by simulating the exceptions, I can repro the NPE everytime even with CPU read. So it's typically a hadoop-aws issue.

```
21/07/22 07:46:53 INFO S3AInputStream: Got exception while trying to read from stream XXXXX trying to recover: java.io.IOException: Hacked --- 
21/07/22 07:46:54 ERROR Executor: Exception in task 0.0 in stage 0.0 (TID 0)
org.apache.spark.SparkException: Exception thrown in awaitResult: 
	at org.apache.spark.util.ThreadUtils$.awaitResult(ThreadUtils.scala:301)
	at org.apache.spark.util.ThreadUtils$.parmap(ThreadUtils.scala:375)
	at org.apache.spark.sql.execution.datasources.parquet.ParquetFileFormat$.readParquetFootersInParallel(ParquetFileFormat.scala:450)
	at org.apache.spark.sql.execution.datasources.parquet.ParquetFileFormat$.$anonfun$mergeSchemasInParallel$1(ParquetFileFormat.scala:496)
	at org.apache.spark.sql.execution.datasources.parquet.ParquetFileFormat$.$anonfun$mergeSchemasInParallel$1$adapted(ParquetFileFormat.scala:490)
	at org.apache.spark.sql.execution.datasources.SchemaMergeUtils$.$anonfun$mergeSchemasInParallel$2(SchemaMergeUtils.scala:75)
	at org.apache.spark.rdd.RDD.$anonfun$mapPartitions$2(RDD.scala:863)
	at org.apache.spark.rdd.RDD.$anonfun$mapPartitions$2$adapted(RDD.scala:863)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:373)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:337)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:90)
	at org.apache.spark.scheduler.Task.run(Task.scala:131)
	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$3(Executor.scala:497)
	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1439)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:500)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.IOException: Could not read footer for file: FileStatus{path=XXXXX; isDirectory=false; length=1403; replication=0; blocksize=0; modification_time=0; access_time=0; owner=; group=; permission=rw-rw-rw-; isSymlink=false; hasAcl=false; isEncrypted=false; isErasureCoded=false}
	at org.apache.spark.sql.execution.datasources.parquet.ParquetFileFormat$.$anonfun$readParquetFootersInParallel$1(ParquetFileFormat.scala:463)
	at org.apache.spark.util.ThreadUtils$.$anonfun$parmap$2(ThreadUtils.scala:372)
	at scala.concurrent.Future$.$anonfun$apply$1(Future.scala:659)
	at scala.util.Success.$anonfun$map$1(Try.scala:255)
	at scala.util.Success.map(Try.scala:213)
	at scala.concurrent.Future.$anonfun$map$1(Future.scala:292)
	at scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:33)
	at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:33)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1402)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:175)
Caused by: java.lang.NullPointerException
	at org.apache.hadoop.fs.s3a.S3AInputStream.lambda$read$3(S3AInputStream.java:453)
	at org.apache.hadoop.fs.s3a.Invoker.once(Invoker.java:109)
	at org.apache.hadoop.fs.s3a.Invoker.lambda$retry$3(Invoker.java:265)
	at org.apache.hadoop.fs.s3a.Invoker.retryUntranslated(Invoker.java:322)
	at org.apache.hadoop.fs.s3a.Invoker.retry(Invoker.java:261)
	at org.apache.hadoop.fs.s3a.Invoker.retry(Invoker.java:236)
	at org.apache.hadoop.fs.s3a.S3AInputStream.read(S3AInputStream.java:449)
	at java.io.DataInputStream.readFully(DataInputStream.java:195)
	at org.apache.parquet.hadoop.util.H1SeekableInputStream.readFully(H1SeekableInputStream.java:51)
	at org.apache.parquet.hadoop.ParquetFileReader.readFooter(ParquetFileReader.java:522)
	at org.apache.parquet.hadoop.ParquetFileReader.readFooter(ParquetFileReader.java:505)
	at org.apache.parquet.hadoop.ParquetFileReader.readFooter(ParquetFileReader.java:499)
	at org.apache.parquet.hadoop.ParquetFileReader.readFooter(ParquetFileReader.java:476)
	at org.apache.spark.sql.execution.datasources.parquet.ParquetFileFormat$.$anonfun$readParquetFootersInParallel$1(ParquetFileFormat.scala:457)
	... 13 more

```

**Comment by wbo4958** [comment] 2021-07-22 01:22
create a hadoop jira https://issues.apache.org/jira/browse/HADOOP-17812 and a PR https://github.com/apache/hadoop/pull/3222

**Comment by wbo4958** [comment] 2021-07-30 23:59
close this issue, since the PR has been merged in to Hadoop trunk.

**Closed by wbo4958** 2021-07-30 23:59 UTC
Labels: bug
