### ISSUE TITLE
[BUG] Code dump in rapids-4-spark-api-validation_2.12 test for ```RegularExpressionTranspilerSuite``` test

### ISSUE THREAD

**Issue by winningsix** [NVIDIA/spark-rapids#9808] opened 2023-11-21 03:15 UTC
**Describe the bug**
Met this issue in https://github.com/NVIDIA/spark-rapids/pull/9760
<head>
It fails in rapids-4-spark-api-validation_2.12. Mvn logs are as below.
<details>

```
[2023-11-21T02:23:51.514Z] - transpile with group index to extract
[2023-11-21T02:23:51.514Z] - compare CPU and GPU: character range including unescaped + and -
[2023-11-21T02:23:51.514Z] - compare CPU and GPU: character range including escaped + and - and d
[2023-11-21T02:23:51.514Z] - compare CPU and GPU: octal
[2023-11-21T02:23:51.514Z] - compare CPU and GPU: find digits
[2023-11-21T02:23:51.514Z] - compare CPU and GPU: replace digits
[2023-11-21T02:23:54.769Z] #
[2023-11-21T02:23:54.769Z] # A fatal error has been detected by the Java Runtime Environment:
[2023-11-21T02:23:54.769Z] #
[2023-11-21T02:23:54.769Z] #  SIGSEGV (0xb) at pc=0x00007efde0cb97fd, pid=60525, tid=0x00007efdf03d9700
[2023-11-21T02:23:54.769Z] #
[2023-11-21T02:23:54.769Z] # JRE version: OpenJDK Runtime Environment (8.0_382-b05) (build 1.8.0_382-8u382-ga-1~20.04.1-b05)
[2023-11-21T02:23:54.770Z] # Java VM: OpenJDK 64-Bit Server VM (25.382-b05 mixed mode linux-amd64 compressed oops)
[2023-11-21T02:23:54.770Z] # Problematic frame:
[2023-11-21T02:23:54.770Z] # J 70656 C2 ai.rapids.cudf.ColumnView.copyToHost(Lai/rapids/cudf/HostMemoryAllocator;)Lai/rapids/cudf/HostColumnVector; (1913 bytes) @ 0x00007efde0cb97fd [0x00007efde0cb8ba0+0xc5d]
[2023-11-21T02:23:54.770Z] #
[2023-11-21T02:23:54.770Z] # Core dump written. Default location: /home/jenkins/agent/workspace/jenkins-rapids_premerge-github-8470/tests/core or core.60525
[2023-11-21T02:23:54.770Z] #
[2023-11-21T02:23:54.770Z] # An error report file with more information is saved as:
[2023-11-21T02:23:54.770Z] # /home/jenkins/agent/workspace/jenkins-rapids_premerge-github-8470/tests/hs_err_pid60525.log
[2023-11-21T02:23:54.770Z] #
[2023-11-21T02:23:54.770Z] # If you would like to submit a bug report, please visit:
[2023-11-21T02:23:54.770Z] #   http://bugreport.java.com/bugreport/crash.jsp
[2023-11-21T02:23:54.770Z] #
[2023-11-21T02:23:54.770Z] [INFO] ------------------------------------------------------------------------
[2023-11-21T02:23:54.770Z] [INFO] Reactor Summary for RAPIDS Accelerator for Apache Spark Root Project 23.12.0-SNAPSHOT:
[2023-11-21T02:23:54.770Z] [INFO] 
[2023-11-21T02:23:54.770Z] [INFO] RAPIDS Accelerator for Apache Spark Root Project ... SUCCESS [ 42.353 s]
[2023-11-21T02:23:54.770Z] [INFO] rapids-4-spark-jdk-profiles_2.12 ................... SUCCESS [  0.429 s]
[2023-11-21T02:23:54.770Z] [INFO] rapids-4-spark-shim-deps-parent_2.12 ............... SUCCESS [ 12.656 s]
[2023-11-21T02:23:54.770Z] [INFO] rapids-4-spark-sql-plugin-api_2.12 ................. SUCCESS [ 19.674 s]
[2023-11-21T02:23:54.770Z] [INFO] RAPIDS Accelerator for Apache Spark SQL Plugin ..... SUCCESS [02:55 min]
[2023-11-21T02:23:54.770Z] [INFO] RAPIDS Accelerator for Apache Spark Shuffle Plugin . SUCCESS [ 16.437 s]
[2023-11-21T02:23:54.770Z] [INFO] RAPIDS Accelerator for Apache Spark Scala UDF Plugin SUCCESS [01:06 min]
[2023-11-21T02:23:54.770Z] [INFO] RAPIDS Accelerator for Apache Spark Delta Lake Stub  SUCCESS [  6.390 s]
[2023-11-21T02:23:54.770Z] [INFO] RAPIDS Accelerator for Apache Spark Aggregator ..... SUCCESS [ 10.901 s]
[2023-11-21T02:23:54.770Z] [INFO] Data Generator ..................................... SUCCESS [ 22.375 s]
[2023-11-21T02:23:54.770Z] [INFO] RAPIDS Accelerator for Apache Spark Distribution ... SUCCESS [06:09 mi]
[2023-11-21T02:23:54.770Z] [INFO] rapids-4-spark-integration-tests_2.12 .............. SUCCESS [02:14 min]
[2023-11-21T02:23:54.770Z] [INFO] RAPIDS Accelerator for Apache Spark Tests .......... FAILURE [26:30 min]
[2023-11-21T02:23:54.770Z] [INFO] rapids-4-spark-api-validation_2.12 ................. SKIPPED
[2023-11-21T02:23:54.770Z] [INFO] ------------------------------------------------------------------------
[2023-11-21T02:23:54.770Z] [INFO] BUILD FAILURE
[2023-11-21T02:23:54.770Z] [INFO] ------------------------------------------------------------------------
[2023-11-21T02:23:54.770Z] [INFO] Total time:  41:08 min
[2023-11-21T02:23:54.770Z] [INFO] Finished at: 2023-11-21T02:23:54Z
[2023-11-21T02:23:54.770Z] [INFO] ------------------------------------------------------------------------
[2023-11-21T02:23:54.770Z] [ERROR] Failed to execute goal org.scalatest:scalatest-maven-plugin:2.0.2:test (test) on project rapids-4-spark-tests_2.12: There are test failures -> [Help 1]
[2023-11-21T02:23:54.770Z] [ERROR] 
[2023-11-21T02:23:54.770Z] [ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[2023-11-21T02:23:54.770Z] [ERROR] Re-run Maven using the -X switch to enable full debug logging.
[2023-11-21T02:23:54.770Z] [ERROR] 
[2023-11-21T02:23:54.770Z] [ERROR] For more information about the errors and possible solutions, please read the following articles:
[2023-11-21T02:23:54.770Z] [ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[2023-11-21T02:23:54.770Z] [ERROR] 
[2023-11-21T02:23:54.770Z] [ERROR] After correcting the problems, you can resume the build with the command
[2023-11-21T02:23:54.770Z] [ERROR]   mvn <args> -rf :rapids-4-spark-tests_2.12
```

**Steps/Code to reproduce bug**
However, I failed to reproduce it in my local desktop. Trigger it again to see whether we stably reproduce this.

**Comment by sameerz** [comment] 2023-11-21 22:32
Duplicate of https://github.com/NVIDIA/spark-rapids/issues/8418

**Closed** 2023-11-21 22:32 UTC
Labels: bug, duplicate
