### ISSUE TITLE
[FEA] Update the function `computeNumJoinRows` in GpuHashJoin.

### ISSUE THREAD

**Issue by HaoYang670** [NVIDIA/spark-rapids#7239] opened 2022-12-05 08:02 UTC
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I wish the RAPIDS Accelerator for Apache Spark would [...]
https://github.com/NVIDIA/spark-rapids/blob/b8c4f364dfccb22ee39a6cf566449f9812493554/sql-plugin/src/main/scala/org/apache/spark/sql/rapids/execution/GpuHashJoin.scala#L262-L270

**Describe the solution you'd like**
We should solve the `TODO` as https://github.com/rapidsai/cudf/issues/9053 has been fixed.

**Describe alternatives you've considered**

**Additional context**
Add any other context, code examples, or references to existing implementations about the feature request here.

**Comment by HaoYang670** [comment] 2022-12-05 08:04
cc @jlowe. Please take a look if you have time. Thank you.

**Comment by jlowe** [comment] 2022-12-05 15:25
This is a duplicate of #2440.  The fix is not as simple as we suspected, as we've tried twice unsuccessfully to use the join output size estimation.  It is possible to complete, but it requires updating the code to support batching _either_ the left or right sides of the join.  Currently it only supports chunking one side, determined statically at query planning time.  It needs to be more dynamic.

**Closed by jlowe** 2022-12-05 15:25 UTC
Labels: duplicate, feature request, ? - Needs Triage
