### ISSUE TITLE
[BUG] test_array_intersect failed in databricks 10.4 runtime and Spark 3.3+

### ISSUE THREAD

**Issue by pxLi** [NVIDIA/spark-rapids#6208] opened 2022-08-03 05:35 UTC
**Describe the bug**
related to https://github.com/NVIDIA/spark-rapids/pull/5958

```
[2022-08-03T05:20:04.980Z] FAILED ../../src/main/python/array_test.py::test_array_intersect[Short][INCOMPAT]
[2022-08-03T05:20:04.980Z] FAILED ../../src/main/python/array_test.py::test_array_intersect[Double][INCOMPAT]
[2022-08-03T05:20:04.980Z] FAILED ../../src/main/python/array_test.py::test_array_intersect[Integer][INCOMPAT]
[2022-08-03T05:20:04.980Z] FAILED ../../src/main/python/array_test.py::test_array_intersect[Long][INCOMPAT]
[2022-08-03T05:20:04.980Z] FAILED ../../src/main/python/array_test.py::test_array_intersect[Byte][INCOMPAT]
[2022-08-03T05:20:04.980Z] FAILED ../../src/main/python/array_test.py::test_array_intersect[Float][INCOMPAT]
```

`AssertionError: CPU and GPU list have different lengths at [0, 'sort_array(array_intersect(a, b), true)'] CPU: 1 GPU: 0`

BTW databricks 9.1 runtime works fine.

**Comment by abellina** [comment] 2022-08-03 14:42
This also failed in other CI jobs (non databricks) for 22.08 or 22.10.

**Comment by NVnavkumar** [comment] 2022-08-03 14:57
> This also failed in other CI jobs (non databricks) for 22.08 or 22.10.

confirmed the failure is in Spark 3.3.0

**Comment by abellina** [comment] 2022-08-03 16:23
I am seeing a related failure in our Yarn test for `test_array_union_before_spark313[Decimal(7,3)]`:
```
cpu = [Decimal('2069.784')], gpu = None
```

**Comment by NVnavkumar** [comment] 2022-08-03 18:21
> > This also failed in other CI jobs (non databricks) for 22.08 or 22.10.
> 
> confirmed the failure is in Spark 3.3.0

The array_intersect test failure looks like a bug in array_intersect that was introduced in Spark 3.3.0.  Here is an example of a test failure with this strange output on the CPU:
```
Row(a=[-3872, -10423, -24617, -13585, -4093, -23070, -8059, -17080], b=[-17558, -29933, -8524, 30046, -24762, None, 23018, 1300, -23335, 13145, -24768], sort_array(array_intersect(a, b), true)=[], sort_array(array_intersect(b, a), true)=[None])
```
It probably came from here: https://github.com/apache/spark/pull/34077

I'm guessing Databricks might have pulled in the same "fix"

I will look into the array_union issue but that looks like a separate issue from this one.

**Comment by NVnavkumar** [comment] 2022-08-04 05:22
Fil

> > > This also failed in other CI jobs (non databricks) for 22.08 or 22.10.
> > 
> > 
> > confirmed the failure is in Spark 3.3.0
> 
> The array_intersect test failure looks like a bug in array_intersect that was introduced in Spark 3.3.0. Here is an example of a test failure with this strange output on the CPU:
> 
> ```
> Row(a=[-3872, -10423, -24617, -13585, -4093, -23070, -8059, -17080], b=[-17558, -29933, -8524, 30046, -24762, None, 23018, 1300, -23335, 13145, -24768], sort_array(array_intersect(a, b), true)=[], sort_array(array_intersect(b, a), true)=[None])
> ```
> 
> It probably came from here: [apache/spark#34077](https://github.com/apache/spark/pull/34077)
> 
> I'm guessing Databricks might have pulled in the same "fix"
> 
> I will look into the array_union issue but that looks like a separate issue from this one.

Filed https://issues.apache.org/jira/browse/SPARK-39976

**Comment by NVnavkumar** [comment] 2022-08-05 00:19
Hmm, I replicated the test scenario on the YARN cluster, and all the tests all passed with the same spark version and via YARN and UCX. This looks like some kind of ephemeral failure at this point. 

> I am seeing a related failure in our Yarn test for `test_array_union_before_spark313[Decimal(7,3)]`:
> 
> ```
> cpu = [Decimal('2069.784')], gpu = None
> ```

**Comment by NVnavkumar** [comment] 2022-08-06 04:13
This failure occurred again. I'm going to file a new issue to track this one.

> Hmm, I replicated the test scenario on the YARN cluster, and all the tests all passed with the same spark version and via YARN and UCX. This looks like some kind of ephemeral failure at this point.
> 
> > I am seeing a related failure in our Yarn test for `test_array_union_before_spark313[Decimal(7,3)]`:
> > ```
> > cpu = [Decimal('2069.784')], gpu = None
> > ```

**Comment by NVnavkumar** [comment] 2022-08-06 04:21
Filed https://github.com/NVIDIA/spark-rapids/issues/6249 for the array_union failure

> This failure occurred again. I'm going to file a new issue to track this one.
> 
> > Hmm, I replicated the test scenario on the YARN cluster, and all the tests all passed with the same spark version and via YARN and UCX. This looks like some kind of ephemeral failure at this point.
> > > I am seeing a related failure in our Yarn test for `test_array_union_before_spark313[Decimal(7,3)]`:
> > > ```
> > > cpu = [Decimal('2069.784')], gpu = None
> > > ```

**Comment by sameerz** [comment] 2022-08-09 00:28
@NVnavkumar please file a follow up issue to revert the changes in https://github.com/NVIDIA/spark-rapids/pull/6223 when a fix goes into Spark, and then close this issue.

**Comment by NVnavkumar** [comment] 2022-08-10 20:04
Filed a followup issue https://github.com/NVIDIA/spark-rapids/issues/6285 to revert the changes once the fix is made in Apache Spark.

**Closed by NVnavkumar** 2022-08-10 20:04 UTC
Labels: bug
