### ISSUE TITLE
[BUG]shuffle file can not be deleted correctly when use RapidsShuffleManager.

### ISSUE THREAD

**Issue by zengruios** [NVIDIA/spark-rapids#6240] opened 2022-08-05 08:15 UTC
**Describe the bug**
Config spark to use RapidsShuffleManager，when shuffle data spill to disk，and then the shuffle data can not be cleand by spark.This will cause disk space to be exhausted.

**Steps/Code to reproduce bug**
1. Config spark to use RapidsShuffleManager.
2. Disable the host memory pool.(spark.rapids.memory.pinnedPool.size=0, spark.rapids.memory.host.pageablePool.size=0, spark.rapids.memory.host.spillStorageSize=-1)
3. Set spark.cleaner.periodicGC.interval=1min.
5. Submit a sql that can cause some shuffle data.
6. Watch the shuffle files under SPARK_LOCAL_DIRS.

**Expected behavior**
When the SQL execute successfully, the shuffle files under SPARK_LOCAL_DIRS will be cleaned by spark.

**Environment details (please complete the following information)**
 - Environment location: [Standalone]
 - Spark configuration settings related to the issue

**Additional context**

**Comment by sameerz** [comment] 2022-08-09 20:42
@abellina can you take a look at this please?

**Comment by abellina** [comment] 2022-08-09 22:42
@zengruios I am looking into this, trying to reproduce the issue on my side. I'll get back to you soon. 

Thanks for this report!

**Comment by abellina** [comment] 2022-08-10 13:56
@zengruios reproduced the issue you reported. This is happening because the `ShuffleBufferCatalog` is using a different block manager than the `RapidsDiskStore`, and so this line fails to delete (because the path is wrong), and we don't print anything out because of the `&& file.exists()`: https://github.com/NVIDIA/spark-rapids/blob/branch-22.10/sql-plugin/src/main/scala/com/nvidia/spark/rapids/ShuffleBufferCatalog.scala#L99

Great catch.

**Comment by abellina** [comment] 2022-08-31 14:07
I assume this issue is fixed now (with https://github.com/NVIDIA/spark-rapids/pull/6318), please let us know if you have further questions @zengruios.

**Closed by abellina** 2022-08-31 14:07 UTC
Labels: bug, shuffle
