### ISSUE TITLE
[BUG] SIGSEGV upon interrupting an array_test 

### ISSUE THREAD

**Issue by gerashegalov** [NVIDIA/spark-rapids#6126] opened 2022-07-27 21:31 UTC
**Describe the bug**
I ran into a SIGSEGV when Ctrl+C an integration test

**Steps/Code to reproduce bug**
It may be specific to a particular test 
```
SPARK_HOME=~/dist/spark-3.2.1-bin-hadoop3.2 ./integration_tests/run_pyspark_from_build.sh -k array_test
```
generated a crash dump
```
Native frames: (J=compiled Java code, j=interpreted, Vv=VM code, C=native code)
C  [cudf6985137822101249781.so+0x145788f]  rmm::mr::owning_wrapper<rmm::mr::limiting_resource_adaptor<rmm::mr::cuda_async_memory_resource>, rmm::mr::cuda_async_memory_resource>::do_allocate(unsigned long, rmm::cuda_stream_view)+0xf

Java frames: (J=compiled Java code, j=interpreted, Vv=VM code)
J 14197  ai.rapids.cudf.Rmm.allocInternal(JJ)J (0 bytes) @ 0x00007f4de3659f44 [0x00007f4de3659f00+0x44]
J 14196 C1 ai.rapids.cudf.Rmm.alloc(JLai/rapids/cudf/Cuda$Stream;)Lai/rapids/cudf/DeviceMemoryBuffer; (28 bytes) @ 0x00007f4de365df14 [0x00007f4de365dc60+0x2b4]
J 20852 C1 ai.rapids.cudf.ColumnView$NestedColumnVector.createNestedColumnVector(Lai/rapids/cudf/DType;JLjava/util/Optional;Lai/rapids/cudf/HostMemoryBuffer;Lai/rapids/cudf/HostMemoryBuffer;Lai/rapids/cudf/HostMemoryBuffer;Ljava/util/List;)Lai/rapids/cudf/ColumnView$NestedColumnVector; (170 bytes) @ 0x00007f4de2892fac [0x00007f4de2892660+0x94c]
J 20849 C1 ai.rapids.cudf.ColumnView$NestedColumnVector.createNewNestedColumnVector(Lai/rapids/cudf/HostColumnVectorCore;)Lai/rapids/cudf/ColumnView$NestedColumnVector; (134 bytes) @ 0x00007f4de38e3a3c [0x00007f4de38e2340+0x16fc]
J 20849 C1 ai.rapids.cudf.ColumnView$NestedColumnVector.createNewNestedColumnVector(Lai/rapids/cudf/HostColumnVectorCore;)Lai/rapids/cudf/ColumnView$NestedColumnVector; (134 bytes) @ 0x00007f4de38e354c [0x00007f4de38e2340+0x120c]
J 22806 C1 ai.rapids.cudf.ColumnView$NestedColumnVector.createColumnVector(Lai/rapids/cudf/DType;ILai/rapids/cudf/HostMemoryBuffer;Lai/rapids/cudf/HostMemoryBuffer;Lai/rapids/cudf/HostMemoryBuffer;Ljava/util/Optional;Ljava/util/List;)Lai/rapids/cudf/ColumnVector; (391 bytes) @ 0x00007f4de4bf9474 [0x00007f4de4bf8f20+0x554]
J 18923 C1 ai.rapids.cudf.HostColumnVector.copyToDevice()Lai/rapids/cudf/ColumnVector; (410 bytes) @ 0x00007f4de27b3e44 [0x00007f4de27b2460+0x19e4]
J 21959 C1 ai.rapids.cudf.HostColumnVector$ColumnBuilder.buildAndPutOnDevice()Lai/rapids/cudf/ColumnVector; (84 bytes) @ 0x00007f4de3fab174 [0x00007f4de3faafe0+0x194]
J 21958 C1 com.nvidia.spark.rapids.GpuColumnVector$GpuColumnarBatchBuilder.buildAndPutOnDevice(I)Lorg/apache/spark/sql/vectorized/ColumnVector; (37 bytes) @ 0x00007f4de3fa7e9c [0x00007f4de3fa7d80+0x11c]
J 24420 C1 com.nvidia.spark.rapids.GpuColumnVector$GpuColumnarBatchBuilderBase.build(I)Lorg/apache/spark/sql/vectorized/ColumnarBatch; (156 bytes) @ 0x00007f4de58d76ac [0x00007f4de58d7440+0x26c]
J 25382 C1 com.nvidia.spark.rapids.RowToColumnarIterator$$Lambda$3498.apply(Ljava/lang/Object;)Ljava/lang/Object; (16 bytes) @ 0x00007f4de155734c [0x00007f4de1557120+0x22c]
J 24579 C2 com.nvidia.spark.rapids.RowToColumnarIterator.$anonfun$buildBatch$1(Lcom/nvidia/spark/rapids/RowToColumnarIterator;Lai/rapids/cudf/NvtxRange;)Lorg/apache/spark/sql/vectorized/ColumnarBatch; (455 bytes) @ 0x00007f4de59ab2d4 [0x00007f4de59aa800+0xad4]
J 26036 C1 com.nvidia.spark.rapids.RowToColumnarIterator$$Lambda$3458.apply(Ljava/lang/Object;)Ljava/lang/Object; (12 bytes) @ 0x00007f4de5df241c [0x00007f4de5df22c0+0x15c]
J 24954 C2 com.nvidia.spark.rapids.Arm.withResource(Ljava/lang/AutoCloseable;Lscala/Function1;)Ljava/lang/Object; (60 bytes) @ 0x00007f4de5abd9cc [0x00007f4de5abd980+0x4c]
J 25502 C1 com.nvidia.spark.rapids.RowToColumnarIterator.next()Ljava/lang/Object; (5 bytes) @ 0x00007f4de1fb3204 [0x00007f4de1fb2b00+0x704]
J 7257 C2 scala.collection.Iterator$$anon$10.next()Ljava/lang/Object; (19 bytes) @ 0x00007f4de151f2e8 [0x00007f4de151f2a0+0x48]
J 24834 C1 com.nvidia.spark.rapids.ColumnarToRowIterator.$anonfun$fetchNextBatch$2(Lcom/nvidia/spark/rapids/ColumnarToRowIterator;Ljava/lang/Object;Lcom/nvidia/spark/rapids/NvtxWithMetrics;)Lscala/None$; (69 bytes) @ 0x00007f4de32ed87c [0x00007f4de32ed5e0+0x29c]
J 23373 C1 com.nvidia.spark.rapids.ColumnarToRowIterator$$Lambda$3632.apply(Ljava/lang/Object;)Ljava/lang/Object; (16 bytes) @ 0x00007f4de246826c [0x00007f4de2468100+0x16c]
J 24954 C2 com.nvidia.spark.rapids.Arm.withResource(Ljava/lang/AutoCloseable;Lscala/Function1;)Ljava/lang/Object; (60 bytes) @ 0x00007f4de5abd9cc [0x00007f4de5abd980+0x4c]
J 23374 C1 com.nvidia.spark.rapids.ColumnarToRowIterator.fetchNextBatch()Lscala/Option; (83 bytes) @ 0x00007f4de532e7c4 [0x00007f4de532de60+0x964]
J 23112 C1 com.nvidia.spark.rapids.ColumnarToRowIterator.loadNextBatch()V (25 bytes) @ 0x00007f4de2970c84 [0x00007f4de29709c0+0x2c4]
J 15467 C2 com.nvidia.spark.rapids.ColumnarToRowIterator.hasNext()Z (62 bytes) @ 0x00007f4de173788c [0x00007f4de1737820+0x6c]
```

[hs_err_pid2024091.log](https://github.com/NVIDIA/spark-rapids/files/9203687/hs_err_pid2024091.log)

**Expected behavior**
graceful exit

**Environment details (please complete the following information)**
 bare metal ubuntu20.04

**Comment by jlowe** [comment] 2024-03-07 21:49
Duplicate of #6001

**Closed by jlowe** 2024-03-07 21:49 UTC
Labels: bug, P1
