### ISSUE TITLE
[DOC] Supported Ops Input/Output section combined with Partitioning section

### ISSUE THREAD

**Issue by tgravescs** [NVIDIA/spark-rapids#2779] opened 2021-06-22 17:41 UTC
## Report incorrect documentation

**Location of incorrect documentation**
https://nvidia.github.io/spark-rapids/docs/supported_ops.html#partitioning

**Describe the problems or issues found in the documentation**
The Input/Output section seems to be combined with the Partitioning section there.  You can see a </table> tag in there and doesn't seem to start a new section.

**Comment by jlowe** [comment] 2021-06-22 18:15
Appears to be something triggered by the Jekyll transform, as the original source at https://github.com/NVIDIA/spark-rapids/blob/gh-pages/docs/supported_ops.md#inputoutput renders correctly in Markdown.

**Comment by sameerz** [comment] 2021-08-05 05:16
@revans2 I think I narrowed this down to two missing closing table row `</tr>` elements:

```diff
--- a/docs/supported_ops.md
+++ b/docs/supported_ops.md
@@ -20899,6 +20899,7 @@ as `a` don't show up in the table. They are controlled by the rules for
 <td> </td>
 <td> </td>
 <td> </td>
+</tr>
 <tr>
 <td>SinglePartition$</td>
 <td>Single partitioning</td>
@@ -20922,6 +20923,7 @@ as `a` don't show up in the table. They are controlled by the rules for
 <td> </td>
 <td> </td>
 <td> </td>
+</tr>
 </table>
```
While the html renderers are forgiving of a missing closing `</tr>` jekyll is not.  I am not quite sure how to insert those elements from this block of code: https://github.com/NVIDIA/spark-rapids/blob/branch-21.10/sql-plugin/src/main/scala/com/nvidia/spark/rapids/TypeChecks.scala#L1616

**Comment by abellina** [comment] 2021-08-05 14:44
It seems that the issue is probably at the partitioning section. There is code here to create a table with variable `rowSpan`, so it's likely to be the culprit.

https://github.com/NVIDIA/spark-rapids/blob/branch-21.10/sql-plugin/src/main/scala/com/nvidia/spark/rapids/TypeChecks.scala#L1597

**Closed** 2021-08-09 03:55 UTC
Labels: documentation
