### ISSUE TITLE
[BUG] hive_delimited_text_test:test_basic_hive_text_read  failing 

### ISSUE THREAD

**Issue by tgravescs** [NVIDIA/spark-rapids#7401] opened 2022-12-20 20:50 UTC
**Describe the bug**

The tests are failing on our Cloudera integration nightly tests:

```
[2022-12-20T17:23:12.781Z] FAILED ../../src/main/python/hive_delimited_text_test.py::test_basic_hive_text_read[hive-delim-text/simple-int-values-StructType([StructField('number', DecimalType(10,2), True)])-{}][APPROXIMATE_FLOAT]

[2022-12-20T17:23:12.781Z] FAILED ../../src/main/python/hive_delimited_text_test.py::test_basic_hive_text_read[hive-delim-text/simple-int-values-StructType([StructField('number', DecimalType(10,3), True)])-{}][APPROXIMATE_FLOAT]

[2022-12-20T17:23:12.781Z] FAILED ../../src/main/python/hive_delimited_text_test.py::test_basic_hive_text_read[hive-delim-text/simple-float-values-StructType([StructField('number', DecimalType(10,3), True)])-{}][APPROXIMATE_FLOAT]

[2022-12-20T17:23:12.781Z] FAILED ../../src/main/python/hive_delimited_text_test.py::test_basic_hive_text_read[hive-delim-text/simple-float-values-StructType([StructField('number', DecimalType(38,10), True)])-{}][APPROXIMATE_FLOAT]

[2022-12-20T17:23:12.781Z] FAILED ../../src/main/python/hive_delimited_text_test.py::test_basic_hive_text_read[hive-delim-text/timestamp-StructType([StructField('ts', TimestampType(), True)])-{}][APPROXIMATE_FLOAT]

[2022-12-20T17:23:12.782Z] FAILED ../../src/main/python/hive_delimited_text_test.py::test_basic_hive_text_read[hive-delim-text/date-StructType([StructField('date', DateType(), True)])-{}][APPROXIMATE_FLOAT]
```

AssertionError: GPU and CPU date values are different at [2, 'date']

**Comment by abellina** [comment] 2022-12-20 21:06
@mythrocks this looks to be the first time that https://github.com/NVIDIA/spark-rapids/pull/7265 is executed in this environment FYI.

**Comment by mythrocks** [comment] 2023-01-25 19:54
This is a dupe of #7423. We will track this there. The tests are currently xfailed for CDH.

**Closed by mythrocks** 2023-01-25 19:54 UTC
Labels: bug
