### ISSUE TITLE
[BUG] `java.lang.IncompatibleClassChangeError: vtable stub` gds standalone test failed

### ISSUE THREAD

**Issue by abellina** [NVIDIA/spark-rapids#3332] opened 2021-08-29 06:07 UTC
The gds test executes NDS q93 and I see: `java.lang.IncompatibleClassChangeError: vtable stub`. From the looks of the stack, it is trying to get an instance of `ILoggerFactory`, according to `LoggerFactory.getLogger`. 

Note that this same sha of the plugin/cudf "succeeded" before where q93 completed with task failures, but the build isn't failing when it should, and I am not sure how far back this issue goes, in either case we fail to fetch from a remote executor during the shuffle. The error here seems new to me. I did not see this `vtable` error in the previous CI run, but I think if triggered the executor logs should be inspected.

Spark version running on the host:
```
ShimLoader: Loading shim for Spark version: 3.0.2
```

With HEAD sha of the plugin (as of the writing of this issue):
```
17:55:57 INFO SQLExecPlugin: RAPIDS Accelerator build: {version=21.10.0-SNAPSHOT. revision=7c9b361f58408779eb67d906b86f9f9d9b964926, cudf_version=21.10.0-SNAPSHOT, branch=HEAD}
17:55:57 INFO SQLExecPlugin: cudf build: {version=21.10.0-SNAPSHOT, revision=4d8e401f778396bd909f5ea0f75b80ec52ebd74c, branch=HEAD}
```

```
Caused by: java.lang.IncompatibleClassChangeError: vtable stub
  at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:363)
  at org.apache.spark.internal.Logging.log(Logging.scala:50)
  at org.apache.spark.internal.Logging.log$(Logging.scala:47)
  at com.nvidia.spark.rapids.shuffle.RapidsShuffleClient.log(RapidsShuffleClient.scala:88)
  at org.apache.spark.internal.Logging.logDebug(Logging.scala:61)
  at org.apache.spark.internal.Logging.logDebug$(Logging.scala:60)
  at com.nvidia.spark.rapids.shuffle.RapidsShuffleClient.logDebug(RapidsShuffleClient.scala:88)
  at com.nvidia.spark.rapids.shuffle.RapidsShuffleClient.$anonfun$doFetch$1(RapidsShuffleClient.scala:177)
  at com.nvidia.spark.rapids.Arm.withResource(Arm.scala:28)
  at com.nvidia.spark.rapids.Arm.withResource$(Arm.scala:26)
  at com.nvidia.spark.rapids.shuffle.RapidsShuffleClient.withResource(RapidsShuffleClient.scala:88)
  at com.nvidia.spark.rapids.shuffle.RapidsShuffleClient.doFetch(RapidsShuffleClient.scala:171)
  at com.nvidia.spark.rapids.shuffle.RapidsShuffleIterator.$anonfun$start$3(RapidsShuffleIterator.scala:274)
  at com.nvidia.spark.rapids.shuffle.RapidsShuffleIterator.$anonfun$start$3$adapted(RapidsShuffleIterator.scala:163)
  at scala.collection.IndexedSeqOptimized.foreach(IndexedSeqOptimized.scala:36)
  at scala.collection.IndexedSeqOptimized.foreach$(IndexedSeqOptimized.scala:33)
  at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:198)
  at com.nvidia.spark.rapids.shuffle.RapidsShuffleIterator.start(RapidsShuffleIterator.scala:163)
  at com.nvidia.spark.rapids.shuffle.RapidsShuffleIterator.next(RapidsShuffleIterator.scala:341)
  ... 50 more
```

**Comment by jlowe** [comment] 2021-09-08 16:11
I'm unable to reproduce this, and thinking about this more, it doesn't really make sense given the stacktrace.  The stacktrace shows `RapidsShuffleClient` is unable to access the `ILoggerFactory` instance due to the vtable stub error, but it also shows  the error occurring during a shuffle fetch, which means we're well into running a Spark query.  `RapidsShuffleClient` is in the `sql-plugin` jar and should have the same classpath as other `sql-plugin` classes.  We definitely logged some things on Spark startup and were able to get through `ILoggerFactory` initialization successfully for those logging messages (e.g.: when RAPIDS Executor plugin initializes RMM pool, `GpuShuffleEnv` logs a message on startup indicating UCX shuffle is configured, etc.).

Therefore I cannot readily explain how some classes that should be using the same classpath were able to successfully initialize the logger but somehow `RapidsShuffleClient` was unable to do so later.

**Comment by jlowe** [comment] 2021-09-09 14:49
Closing this as unreproducible.  We can reopen if it occurs again.

**Closed by jlowe** 2021-09-09 14:49 UTC
Labels: bug, P1
