### ISSUE TITLE
[BUG] Failed test_initcap[DATAGEN_SEED=1701454561, INCOMPAT] on CI

### ISSUE THREAD

**Issue by cindyyuanjiang** [NVIDIA/spark-rapids#9930] opened 2023-12-02 02:33 UTC
**Describe the bug**
Failed integration test with mismatch CPU and GPU outputs. Pipeline: `rapids-it-azure-databricks-10.4`

Details:

```
FAILED ../../src/main/python/string_test.py::test_initcap[DATAGEN_SEED=1701454561, INCOMPAT] - AssertionError: GPU and CPU string values are different at [146, 'initcap(a)']

--- CPU OUTPUT

[2023-12-01T18:20:27.553Z] +++ GPU OUTPUT

[2023-12-01T18:20:27.553Z] @@ -144,7 +144,7 @@

[2023-12-01T18:20:27.553Z]  Row(initcap(a)='%a@1é--ⱥb5bÿ17ⱥ\néaⱥÿ3ⱥa5ÿ-7b7-_\r\n5ⱥ3a17b53-bⱥa%7 Ÿb357ⱥbaÿ1ÿb_1a\r\rb-35@béé@é_b55%\n ')

[2023-12-01T18:20:27.553Z]  Row(initcap(a)='Ÿ17ⱥÿ@73ab1@b1ⱥ\r\n7aabⱥ_aÿ_éÿb1%ÿ\n7ⱥ_%a3@é%bⱥÿ71\t 3aaⱥ_%%%@b7@b_é\t\rab@é@_3ÿb5-ÿé35\n\r')

[2023-12-01T18:20:27.553Z]  Row(initcap(a)='5-57aa_@ÿbⱥ-abé\r 33a5a@1ÿé_é7--3  A7@é53_éÿaⱥb75\rbaab_a-é_ba_7_7\n\ta5_aé@5-5_1b7ÿ5  ')

[2023-12-01T18:20:27.553Z] -Row(initcap(a)='ß\x19p1ç_õß\x00\x97')

[2023-12-01T18:20:27.553Z] +Row(initcap(a)='SS\x19p1ç_õß\x00\x97')

[2023-12-01T18:20:27.553Z]  Row(initcap(a)='Éaⱥa5bÿ_bab_153\t_7a53-ÿ@@5@bÿⱥⱥ\n Ⱥa7-%@é11773ⱥa@\r\n7357aⱥ1-1_é%1-@\t\n-ⱥa15b1-73515éÿ\t\r')

[2023-12-01T18:20:27.553Z]  Row(initcap(a)='--aⱥé57a7-7a7éb\t 7ÿÿ%5-a_ÿb_%3b5 \nb1%-b7ba%73ÿⱥbⱥ\naÿÿ3%ⱥ5bbb55bb-\t\t3é-ⱥⱥb_aa-bba33\r\r')

[2023-12-01T18:20:27.553Z]  Row(initcap(a)='@b_77-é_%aa%7ÿb\n Bé1_5é3b@é1551b \na-3%3-3aÿ%%aaé3\t\tⱥb7ⱥ5731a5@5a7ⱥ  Bé1a@ab3a71%15é\n\r')
```

**Steps/Code to reproduce bug**
Integration test

**Expected behavior**
Should pass

**Comment by sameerz** [comment] 2023-12-04 00:48
I believe this is a dupe of https://github.com/NVIDIA/spark-rapids/issues/9247

**Closed** 2023-12-05 21:44 UTC
Labels: bug, duplicate, ? - Needs Triage
