### ISSUE TITLE
SPARK-35881 has added support for columnar execution of final querystage in AdaptiveSparkPlanExec

### ISSUE THREAD

**Issue by razajafri** [NVIDIA/spark-rapids#3238] opened 2021-08-17 02:07 UTC
I am not very sure about this but AQE might be affected by this change

[SPARK-35881 ](https://github.com/apache/spark/commit/f9f5656491)

**Comment by jlowe** [comment] 2021-08-17 13:39
This is arguably a duplicate of #2834.  The plugin-side changes are being investigated by @andygrove in #3144.

**Closed** 2021-08-17 20:11 UTC
Labels: bug, duplicate, audit_3.2.0
