### ISSUE TITLE
[BUG] Reading Parquet written with INT96 ts doesn't match the CPU when reading back

### ISSUE THREAD

**Issue by razajafri** [NVIDIA/spark-rapids#1007] opened 2020-10-22 18:57 UTC
**Describe the bug**
When running the following test that generates a single column DF, it fails when ts_write is 'INT96'. The dates are different on cpu and gpu

```
@pytest.mark.parametrize('data_gen', [TimestampGen()], ids=idfn)
@pytest.mark.parametrize('ts_write', ['INT96', 'TIMESTAMP_MICROS', 'TIMESTAMP_MILLIS'])
@pytest.mark.parametrize('enableVectorized', ['true', 'false'], ids=idfn)
@allow_non_gpu('CollectLimitExec', 'DataWritingCommandExec')
@ignore_order
def test_cache_columnar(spark_tmp_path, data_gen, enableVectorized, ts_write):
    data_path_gpu = spark_tmp_path + '/PARQUET_DATA'
    def read_parquet_cached(data_path):
        def write_read_parquet_cached(spark):
            df = unary_op_df(spark, data_gen)
            df.write.mode('overwrite').parquet(data_path)
            cached = spark.read.parquet(data_path)#.cache()
            cached.count()
            return cached.select(f.col("a"))
        return write_read_parquet_cached
    # rapids-spark doesn't support LEGACY read for parquet
    conf={'spark.sql.legacy.parquet.datetimeRebaseModeInWrite': 'CORRECTED',
          'spark.sql.legacy.parquet.datetimeRebaseModeInRead' : 'CORRECTED',
          'spark.sql.inMemoryColumnarStorage.enableVectorizedReader' : enableVectorized,
          'spark.sql.parquet.outputTimestampType': ts_write}

    assert_gpu_and_cpu_are_equal_collect(read_parquet_cached(data_path_gpu), conf)

```
**Steps/Code to reproduce bug**
Run the above test in python 

**Expected behavior**
The above test should pass

**Comment by jlowe** [comment] 2020-10-28 15:36
This is a duplicate of #132.  Changing the test to only generate timestamps from 1590 or afterwards allows the test to pass.  The [issue with timestamps before 1590 is documented](https://github.com/NVIDIA/spark-rapids/blob/branch-0.3/docs/compatibility.md#parquet) and #132 tracks the issue.

**Closed by jlowe** 2020-10-28 15:36 UTC
Labels: P1, bug
