### ISSUE TITLE
[TASK] Rename cache serializer to a common name

### ISSUE THREAD

**Issue by jlowe** [NVIDIA/spark-rapids#2975] opened 2021-07-20 20:22 UTC
After #2905 all that remains is the Spark 3.1.1 cache serializer but it is common to all Spark versions that support a pluggable cache serializer.  This class should be renamed to a common package and moved out of the Spark 3.1.1 shim project.

**Comment by sperlingxx** [comment] 2021-08-03 09:58
I am wondering how to adapt Spark 3.0.x if we move the serializer to common package. The `CachedBatchSerializer` was introduced at 3.1.

**Comment by jlowe** [comment] 2021-08-03 13:27
The module would be common to all Spark versions >= 3.1.1 rather than in a specific shim directory as it is now.  That module would not compile against Spark 3.0.x.

**Comment by Salonijain27** [comment] 2021-09-14 21:27
duplicate of #3314

**Closed by Salonijain27** 2021-09-14 21:27 UTC
Labels: task
