### ISSUE TITLE
[BUG] [AUDIT] [SPARK-42478] Make a serializable jobTrackerId instead of a non-serializable JobID in FileWriterFactory

### ISSUE THREAD

**Issue by abellina** [NVIDIA/spark-rapids#8114] opened 2023-04-14 15:14 UTC
The changes in this PR make the jobId is consistent in task re-attempts in the file writers (e.g. `GpuFileFormatWriter`) https://github.com/apache/spark/commit/eb8fa5b713. It looks like this has gone from a date, to a date with seconds, to adding a random number to this jobId. On the retry, according to the comments, jobId should stay the same according to the Hadoop committer interface.

The issue was fixed in 3.4, but then also merged to 3.3 and 3.2. Looking at our code, I see our spark340 shim already calls `createJobTrackerID`, which is later passed to `createJobId` to recover the consistent `jobId`. I do not see these calls in our 3.3 and 3.2 lines of shims, and I am wondering if we need it.

**Comment by mattahrens** [comment] 2023-04-18 20:39
Scope: investigate if change we made in 3.4 is needed for our 3.3 and 3.2 shims.

**Comment by tgravescs** [comment] 2023-05-26 20:07
so the issue SPARK-42478 mentioned here is fine, because its fixing a v2 datasource code in Spark as being not serializable. The problem is that the reason this came about was because of https://issues.apache.org/jira/browse/SPARK-41448, which in our audit (https://github.com/NVIDIA/spark-rapids/issues/7491) we said was fixed by https://github.com/NVIDIA/spark-rapids/pull/7542. Unfortunately that PR only updated it for 3.4.0.  SPARK-41448 applies to 3.2.3 and 3.3.2 - well that is where fix went, really it affects 3.0 and newer releases. That could be a correct ness issue so we need to fix.

**Closed** 2023-05-31 19:07 UTC
Labels: bug, feature request, audit_3.3.0, audit_3.2.1, audit_3.4.0
