### ISSUE TITLE
Enable `test_read_repeated_no_annotation` which is set to xfail  

### ISSUE THREAD

**Issue by razajafri** [NVIDIA/spark-rapids#8710] opened 2023-07-13 23:04 UTC
Once https://github.com/rapidsai/cudf/issues/13664 is fixed we need to remove xfail from `test_read_repeated_no_annotation` in `parquet_test.py`

**Comment by razajafri** [comment] 2023-07-13 23:04
depends on rapidsai/cudf#13664

**Comment by jlowe** [comment] 2023-07-14 13:55
Duplicate of #8631.

**Closed** 2023-07-14 13:55 UTC
Labels: bug, duplicate, ? - Needs Triage
