### ISSUE TITLE
[FEA][Audit] [SPARK-37455][SQL] Replace hash with sort aggregate if child is already sorted

### ISSUE THREAD

**Issue by nartal1** [NVIDIA/spark-rapids#4498] opened 2022-01-11 04:25 UTC
**Is your feature request related to a problem? Please describe.**
This PR https://github.com/apache/spark/commit/544865db77,  if the child of hash aggregate is already sorted on group-by columns, they replace hash aggregate with sort aggregate for better performance. 
From the PR, it looks like its an optimization in AQE. 
I don't think we need to implement this. Created the issue to get feedback from others. 

There is a followon of the above PR - https://github.com/apache/spark/commit/41a940f071

**Comment by jlowe** [comment] 2022-01-11 23:00
We don't need to worry about the Spark change, as we replace all aggregates, sort or otherwise, with GpuHashAggregates and remove the corresponding pre-sort if it was a sort-based aggregate.  Therefore I don't see this as an audit issue, as we will still produce proper plans and do a hash aggregate.

However we could benefit from similar logic.  When we are going to put in a GpuHashAggregate but the reported child ordering matches the grouping keys then we could hint to libcudf that the data is already sorted.  There have been libcudf bugs in the past in sorted aggregates, so we need explicit testing to verify that the optimization is working as intended and producing correct output.

**Comment by jlowe** [comment] 2022-01-11 23:07
I don't think this is a high priority change.  This optimization is probably more relevant for CPU plans because it's common to have a join followed by an aggregate on the same join keys.  SortMergeJoin produces output sorted on the join keys, but we replace a SortMergeJoin with a GPU hash join and therefore don't have the same benefit of sorted output from the join.

**Comment by mattahrens** [comment] 2022-05-03 18:19
Closing as won't fix for now

**Closed by mattahrens** 2022-05-03 18:19 UTC
Labels: performance
