### ISSUE TITLE
[BUG] Query failed if reading a Hive partition table with partition key column is a Boolean data type, and if spark.rapids.alluxio.pathsToReplace is set

### ISSUE THREAD

**Issue by viadea** [NVIDIA/spark-rapids#6029] opened 2022-07-19 17:39 UTC
Query failed if reading a Hive partition table with partition key column is a Boolean data type when `spark.rapids.alluxio.pathsToReplace` is set.

**Env:**
Spark standalone cluster(spark-3.2.1-bin-hadoop3.2)
apache-hive-3.1.2-bin
Spark RAPIDS 22.06GA

Below config is set in spark-defaults.conf
```
spark.rapids.alluxio.pathsToReplace s3a://abc/->alluxio://masterip:19998/
```

**Mini repro**
1. Spark-SQL to create a sample Hive partition table and generate sample data.
```
CREATE TABLE issue6026_local (
  k1 BOOLEAN,
  c1 STRING )
USING parquet
PARTITIONED BY (k1)
LOCATION '/home/xxx/data/hive/issue6026_local';

INSERT INTO issue6026_local(k1,c1) select CAST('false' AS BOOLEAN), 'abc';
```

2. GPU query failed
```
set spark.rapids.sql.enabled=true;
select * from issue6026_local;
Caused by: java.lang.IllegalArgumentException: 'false: class org.apache.spark.unsafe.types.UTF8String' is not supported for BooleanType, expecting Boolean.
```

Full stacktrace:
```
Caused by: java.lang.IllegalArgumentException: 'false: class org.apache.spark.unsafe.types.UTF8String' is not supported for BooleanType, expecting Boolean.
	at com.nvidia.spark.rapids.GpuScalar$.from(literals.scala:315)
	at com.nvidia.spark.rapids.ColumnarPartitionReaderWithPartitionValues$.$anonfun$createPartitionValues$2(ColumnarPartitionReaderWithPartitionValues.scala:69)
	at com.nvidia.spark.rapids.RapidsPluginImplicits$MapsSafely.$anonfun$safeMap$1(implicits.scala:216)
	at com.nvidia.spark.rapids.RapidsPluginImplicits$MapsSafely.$anonfun$safeMap$1$adapted(implicits.scala:213)
	at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:62)
	at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:55)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:49)
	at com.nvidia.spark.rapids.RapidsPluginImplicits$MapsSafely.safeMap(implicits.scala:213)
	at com.nvidia.spark.rapids.RapidsPluginImplicits$AutoCloseableProducingSeq.safeMap(implicits.scala:248)
	at com.nvidia.spark.rapids.ColumnarPartitionReaderWithPartitionValues$.createPartitionValues(ColumnarPartitionReaderWithPartitionValues.scala:68)
	at com.nvidia.spark.rapids.MultiFileReaderFunctions.$anonfun$addPartitionValues$1(GpuMultiFileReader.scala:74)
	at scala.Option.map(Option.scala:230)
	at com.nvidia.spark.rapids.MultiFileReaderFunctions.addPartitionValues(GpuMultiFileReader.scala:71)
	at com.nvidia.spark.rapids.MultiFileReaderFunctions.addPartitionValues$(GpuMultiFileReader.scala:66)
	at com.nvidia.spark.rapids.MultiFileCoalescingPartitionReaderBase.addPartitionValues(GpuMultiFileReader.scala:609)
	at com.nvidia.spark.rapids.MultiFileCoalescingPartitionReaderBase.$anonfun$addAllPartitionValues$1(GpuMultiFileReader.scala:1072)
	at scala.Option.map(Option.scala:230)
	at com.nvidia.spark.rapids.MultiFileCoalescingPartitionReaderBase.addAllPartitionValues(GpuMultiFileReader.scala:1066)
	at com.nvidia.spark.rapids.MultiFileCoalescingPartitionReaderBase.$anonfun$readBatch$1(GpuMultiFileReader.scala:825)
	at com.nvidia.spark.rapids.Arm.withResource(Arm.scala:28)
	at com.nvidia.spark.rapids.Arm.withResource$(Arm.scala:26)
	at com.nvidia.spark.rapids.FilePartitionReaderBase.withResource(GpuMultiFileReader.scala:264)
	at com.nvidia.spark.rapids.MultiFileCoalescingPartitionReaderBase.readBatch(GpuMultiFileReader.scala:797)
	at com.nvidia.spark.rapids.MultiFileCoalescingPartitionReaderBase.next(GpuMultiFileReader.scala:783)
	at com.nvidia.spark.rapids.PartitionIterator.hasNext(dataSourceUtil.scala:29)
	at com.nvidia.spark.rapids.MetricsBatchIterator.hasNext(dataSourceUtil.scala:46)
	at org.apache.spark.InterruptibleIterator.hasNext(InterruptibleIterator.scala:37)
	at org.apache.spark.sql.rapids.GpuFileSourceScanExec$$anon$1.hasNext(GpuFileSourceScanExec.scala:420)
	at com.nvidia.spark.rapids.ColumnarToRowIterator.$anonfun$fetchNextBatch$2(GpuColumnarToRowExec.scala:239)
	at com.nvidia.spark.rapids.Arm.withResource(Arm.scala:28)
	at com.nvidia.spark.rapids.Arm.withResource$(Arm.scala:26)
	at com.nvidia.spark.rapids.ColumnarToRowIterator.withResource(GpuColumnarToRowExec.scala:187)
	at com.nvidia.spark.rapids.ColumnarToRowIterator.fetchNextBatch(GpuColumnarToRowExec.scala:238)
	at com.nvidia.spark.rapids.ColumnarToRowIterator.loadNextBatch(GpuColumnarToRowExec.scala:215)
	at com.nvidia.spark.rapids.ColumnarToRowIterator.hasNext(GpuColumnarToRowExec.scala:255)
	at scala.collection.Iterator$$anon$10.hasNext(Iterator.scala:460)
	at org.apache.spark.sql.execution.SparkPlan.$anonfun$getByteArrayRdd$1(SparkPlan.scala:349)
	at org.apache.spark.rdd.RDD.$anonfun$mapPartitionsInternal$2(RDD.scala:898)
	at org.apache.spark.rdd.RDD.$anonfun$mapPartitionsInternal$2$adapted(RDD.scala:898)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:373)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:337)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:90)
	at org.apache.spark.scheduler.Task.run(Task.scala:131)
	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$3(Executor.scala:506)
	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1462)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:509)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

3. CPU query works fine
```
set spark.rapids.sql.enabled=false;
spark-sql> select * from issue6026_local;
abc	false
Time taken: 0.206 seconds, Fetched 1 row(s)

```

**Comment by viadea** [comment] 2022-07-19 19:01
Currently I can not reproduce this issue on Databricks 10.4ML LTS.

**Comment by viadea** [comment] 2022-07-19 19:42
If I remove the setting `spark.rapids.alluxio.pathsToReplace` , then the query works fine on GPU using our plugin.

Note: Above test hive table is NOT on S3, and it is just a local table.

**Comment by sameerz** [comment] 2022-07-19 20:07
Possible dupe of https://github.com/NVIDIA/spark-rapids/issues/6026, @tgravescs will investigate.

**Comment by tgravescs** [comment] 2022-07-19 22:06
the issue looks like its in the AlluxioUtils.replacePathIfNeeded where even though it doesn't replace any paths, it infers the partitionSpec and it is getting the partition key as a string rather than boolean.

**Comment by tgravescs** [comment] 2022-07-22 17:59
so the code path here is slightly different from https://github.com/NVIDIA/spark-rapids/issues/6026. In this case the datatype are not know at all so we try to infer them which ends up calling inferPartitionColumnValue and it doesn't handle Boolean type.  In the 6026 the type for patition is specified in userSpecifiedDataTypes.   The spark function inferPartitionColumnValue doesn't handle Boolean types so it always comes out String here.

**Closed** 2022-08-01 13:45 UTC
Labels: bug, P1
