### ISSUE TITLE
[BUG] `datasourcev2_read_test.py` test FAILED on Dataproc

### ISSUE THREAD

**Issue by NvTimLiu** [NVIDIA/spark-rapids#1686] opened 2021-02-08 11:33 UTC
**Describe the bug**
Tests FAILED on Dataproc only. This should be a Dataproc spark runtime issue. The `arrow-vector-1.0.1.jar` on Dataproc does NOT match our spark-rapids 3.0.1 shim layer: com.nvidia.spark.rapids.shims.spark300.Spark300Shims.`getArrowDataBuf(Spark300Shims.scala:459)`

_getArrowDataBuf() EXPECT type `io.netty.buffer.ArrowBuf`, while the result is `org.apache.arrow.memory.ArrowBuf`_

##### `ON DATAPROC` :  ls /usr/lib/spark/jars/arrow-vector-1.0.1.jar
_**/usr/lib/spark/jars/arrow-vector-1.0.1.jar**_
In arrow-vector-1.0.1.jar :  **public abstract org.apache.arrow.memory.ArrowBuf getDataBuffer();**

##### By compare, PASS `on EMR`: $ ls /usr/lib/spark/jars/arrow-vector-0.15.1.jar
_**/usr/lib/spark/jars/arrow-vector-0.15.1.jar**_
arrow-vector-0.15.1.jar:   **public abstract io.netty.buffer.ArrowBuf getDataBuffer();**

_19:21:22  E                   : org.apache.spark.SparkException: Job aborted due to stage failure: Task 0 in stage 12138.0 failed 4 times, most recent failure: Lost task 0.3 in stage 12138.0 (TID 100402, rapids-it-83-w-1.c.rapids-spark.internal, executor 2): java.lang.NoSuchMethodError: org.apache.arrow.vector.**ValueVector.getDataBuffer()Lio/netty/buffer/ArrowBuf;**
19:21:22  E                   	at com.nvidia.spark.rapids.shims.spark300.Spark300Shims.getArrowDataBuf(Spark300Shims.scala:459)
19:21:22  E                   	at_ 

19:21:22  FAILED src/main/python/datasourcev2_read_test.py::test_read_int - py4j.protoc...
19:21:22  FAILED src/main/python/datasourcev2_read_test.py::test_read_strings - py4j.pr...
19:21:22  FAILED src/main/python/datasourcev2_read_test.py::test_read_all_types - py4j....
19:21:22  FAILED src/main/python/datasourcev2_read_test.py::test_read_arrow_off - py4j....

**Comment by NvTimLiu** [comment] 2021-02-08 11:35
Add @tgravescs

**Comment by tgravescs** [comment] 2021-02-08 18:43
the issue is dataproc has diffferent arrow jars that don't match spark 3.0.1 apache

```

tgraves@tgraves-test-m:~$ spark-submit --version
Welcome to
      ____              __
     / __/__  ___ _____/ /__
    _\ \/ _ \/ _ `/ __/  '_/
   /___/ .__/\_,_/_/ /_/\_\   version 3.0.1
      /_/
                        
Using Scala version 2.12.12, OpenJDK 64-Bit Server VM, 1.8.0_275
Branch HEAD
Compiled by user  on 2020-12-17T19:12:12Z
Revision 5c02a8d75f580b089804b7399a062b94e6b71ac7
Url https://bigdataoss-internal.googlesource.com/third_party/apache/spark
Type --help for more information.
tgraves@tgraves-test-m:~$ 
tgraves@tgraves-test-m:~$ 
tgraves@tgraves-test-m:~$ ls -1 /usr/lib/spark/jars/*arrow*
/usr/lib/spark/jars/arrow-format-1.0.1.jar
/usr/lib/spark/jars/arrow-memory-core-1.0.1.jar
/usr/lib/spark/jars/arrow-memory-netty-1.0.1.jar
/usr/lib/spark/jars/arrow-vector-1.0.1.jar
```

**Comment by tgravescs** [comment] 2021-02-08 18:44
apache spark uses:
/spark-3.0.1-bin-hadoop3.2/jars/arrow-vector-0.15.1.jar

The shim layer takes care of this for spark 3.1.1 but here dataproc broke that

**Comment by tgravescs** [comment] 2021-02-08 20:17
iut looks like the latest verison of dataproc is now 3.1.1 so we should just change to use that and see if tests pass

**Comment by tgravescs** [comment] 2021-02-09 02:14
the latest dataproc image actually works for this so closing

**Closed by tgravescs** 2021-02-09 02:14 UTC
Labels: ? - Needs Triage, bug
