### ISSUE TITLE
Make premerge build test with a jar containing a minimal set of Spark versions

### ISSUE THREAD

**Issue by tgravescs** [NVIDIA/spark-rapids#3586] opened 2021-09-21 19:27 UTC
**Is your feature request related to a problem? Please describe.**
we should change the premerge to test with at least a couple of versions of spark combined into the jar. The nightly does this but it would be good to move this up to catch any issues earlier.

**Comment by Salonijain27** [comment] 2021-09-28 20:43
duplicate of #3654

**Closed by Salonijain27** 2021-09-28 20:43 UTC
Labels: ? - Needs Triage, task
