### ISSUE TITLE
[BUG] Mixing parquet input files with different schemas results in crashes

### ISSUE THREAD

**Issue by revans2** [NVIDIA/spark-rapids#5619] opened 2022-05-24 19:59 UTC
**Describe the bug**
I have a dataset with files that have two different groups of schemas. If I do a query where some of the files will return no data (none of the columns match) then I get a crash.

**Steps/Code to reproduce bug**
```
Seq("A", "B", "C").toDF("first").write.mode("overwrite").parquet("/tmp/data/first")
Seq(("A", 1), ("B", 2), ("C", 3)).toDF("first", "second").write.mode("overwrite").parquet("/tmp/data/second")
spark.read.option("mergeSchema", "true").parquet("/tmp/data/{second,first}").selectExpr("COUNT(1)", "COUNT(second)").show()
```

```
Caused by: java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
  at java.util.ArrayList.rangeCheck(ArrayList.java:659)
  at java.util.ArrayList.get(ArrayList.java:435)
  at java.util.Collections$UnmodifiableList.get(Collections.java:1311)
  at org.apache.parquet.hadoop.metadata.BlockMetaData.getStartingPos(BlockMetaData.java:103)
  at org.apache.parquet.format.converter.ParquetMetadataConverter.toParquetMetadata(ParquetMetadataConverter.java:209)
  at org.apache.parquet.format.converter.ParquetMetadataConverter.toParquetMetadata(ParquetMetadataConverter.java:197)
  at com.nvidia.spark.rapids.ParquetPartitionReaderBase.writeFooter(GpuParquetScan.scala:1112)
  at com.nvidia.spark.rapids.ParquetPartitionReaderBase.writeFooter$(GpuParquetScan.scala:1104)
  at com.nvidia.spark.rapids.ParquetPartitionReader.writeFooter(GpuParquetScan.scala:2099)
  at com.nvidia.spark.rapids.ParquetPartitionReaderBase.calculateParquetFooterSize(GpuParquetScan.scala:1070)
  at com.nvidia.spark.rapids.ParquetPartitionReaderBase.calculateParquetFooterSize$(GpuParquetScan.scala:1063)
  at com.nvidia.spark.rapids.ParquetPartitionReader.calculateParquetFooterSize(GpuParquetScan.scala:2099)
```

If I change the query it to read something that is common, or read nothing from both it works.

```
spark.read.option("mergeSchema", "true").parquet("/tmp/data/{second,first}").selectExpr("COUNT(1)").show()
spark.read.option("mergeSchema", "true").parquet("/tmp/data/{second,first}").selectExpr("COUNT(1)", "COUNT(first)").show()
```

Note that this appears to work correctly with ORC for some reason, but not with parquet. Although it would be good to do more testing to be sure.

**Expected behavior**
No crashes

**Environment details (please complete the following information)**
 - Environment location: [Standalone, YARN, Kubernetes, Cloud(specify cloud provider)]
 - Spark configuration settings related to the issue

**Additional context**

**Comment by thirtiseven** [comment] 2022-08-16 12:49
Those codes won't crash and get the correct result now.  
I think the bug is caused by reading a non-existent column, which causes the clipped schema to be empty, but cudf does not support this case and generates this exception. 
This bug should have been fixed by #5674. It fixed reading ORC/PARQUET over empty clipped schema by bypassing the cuDF table reader call. The sample code in this issue works fine after this commit. 
Can we close this issue?  
Related issues: #5672 #5694

**Comment by GaryShen2008** [comment] 2022-08-17 02:47
Hi @revans2, can you help check if we can close this issue based on above comment?

**Comment by revans2** [comment] 2022-08-17 21:13
@GaryShen2008 and @thirtiseven Sorry I have been really busy. The test is the same as what I showed in the description.

```
Seq("A", "B", "C").toDF("first").write.mode("overwrite").parquet("/tmp/data/first")
Seq(("A", 1), ("B", 2), ("C", 3)).toDF("first", "second").write.mode("overwrite").parquet("/tmp/data/second")
spark.read.option("mergeSchema", "true").parquet("/tmp/data/{second,first}").selectExpr("COUNT(1)", "COUNT(second)").show()```

I am fine if you run it and it if the results look the same on the CPU and GPU then just close this.

**Comment by thirtiseven** [comment] 2022-08-18 01:13
Ok, the results look the same.

**Closed by thirtiseven** 2022-08-18 01:13 UTC
Labels: bug, P2
