### ISSUE TITLE
[BUG] In CSV parsing a date from a timestamp formatted column produces incorrect results

### ISSUE THREAD

**Issue by revans2** [NVIDIA/spark-rapids#869] opened 2020-09-28 18:15 UTC
**Describe the bug**
In the integration tests for csv `test_basic_read` for ts.csv when the schema says it should be a date produces results that cause an error when pulling them back to python because they are outside of the range that is supported by python, but the input year is 2020.

This was originally marked as #122 but that was recently fixed in cudf, but this issue remains.

**Comment by sameerz** [comment] 2020-11-10 21:15
This is a duplicate of issue #1091.  We will keep that issue since it has more detail.  

A side note, we need to update the [documentation](https://nvidia.github.io/spark-rapids/docs/compatibility.html#csv-dates
) to refer to this issue.

**Closed by sameerz** 2020-11-10 21:15 UTC
Labels: P3, SQL, bug, duplicate
