### ISSUE TITLE
[FEA] Add Hive UDF support for urlDecoder

### ISSUE THREAD

**Issue by kuhushukla** [NVIDIA/spark-rapids#1373] opened 2020-12-11 15:28 UTC
**Is your feature request related to a problem? Please describe.**

With https://github.com/rapidsai/cudf/pull/6972 and possibly other changes to support hive udfs, the plugin should allow for hive udfs with url decoding to work on the gpu.

**Comment by jlowe** [comment] 2020-12-11 15:41
This is a duplicate of #1352.

**Closed by jlowe** 2020-12-11 15:41 UTC
Labels: ? - Needs Triage, feature request
