### ISSUE TITLE
[BUG] Databricks build must run before the rapids nightly

### ISSUE THREAD

**Issue by tgravescs** [NVIDIA/spark-rapids#1466] opened 2021-01-07 15:58 UTC
**Describe the bug**
the databricks nightly build has to run before the rapids nightly because it builds the databricks shim layer jar that gets combined into the rapids nightly build to be published. The databricks build is currently running after it which means the code is a day old.

Ideally we could trigger builds again since everything is migrated.

**Comment by NvTimLiu** [comment] 2021-01-08 03:59
@tgravescs Could you please help to review PR: https://gitlab-master.nvidia.com/nvspark/blossom-jenkins/-/merge_requests/37
Move Databricks nightly pipeline 4 hours ahead (databricks build takes 3.5 hours) of spark-rapids nightly pipeline, to make sure Databricks jars have already built out and deployed before spark-rapids nightly pipeline runs.

branch-0.4: databricks nightly 20:00 PST--> spark-rapids nightly 00:00 PST

branch-0.3: databricks nightly 14:00 PST--> spark-rapids nightly 18:00 PST

**Comment by tgravescs** [comment] 2021-01-08 14:33
This is ok as it should normally work but you still have the issue if it fails you get the wrong jar.

Can we add triggers in the blossom builds?

**Comment by NvTimLiu** [comment] 2021-01-09 04:04
@tgravescs Do you mean instead of the timeline triggers "branch-0.4: databricks nightly 20:00 PST--> spark-rapids nightly 00:00 PST", we add trigger in spark-rapids nightly pipeline like this?
Blossom nightly -->**stage** (running databricks nightly and PASS)  --> **stage** （spark-rapids nightly build）



If so, seems rapids nightly will NOT run if databricks nightly FAILs.

**Comment by tgravescs** [comment] 2021-01-11 14:28
that is correct, triggers between the different jobs and yes if the data bricks nightly fails then the other won't run and package an out of date version. This prevents us from getting an older version of the data bricks jar in a newer version of the spark rapids jar. this has now caused us 2 separate incidents where databricks IT tests fail and we had to investigate.  the good thing is that we wouldn't hit that issue the bad thing is we don't get newer versions of all the other shims.  @jlowe thoughts on this?

**Comment by jlowe** [comment] 2021-01-11 14:55
IMO we shouldn't release something that's half-baked, snapshot or otherwise.  Otherwise we run the risk of running into inconsistency problems as @tgravescs mentioned.  So I agree, if Databricks build fails then we're not ready to release a new snapshot version of the plugin because the Databricks shim is part of that plugin.

If the Databricks shim build regularly blocks snapshots being published then we'll either need to root cause and address why that is the case or move the Databricks shim into a separate jar.

**Comment by NvTimLiu** [comment] 2021-01-12 09:49
@jlowe @tgravescs  Ok, Let remove rapids nightly cron, and add the trigger from databricks nightly pipeline 👍 

https://gitlab-master.nvidia.com/nvspark/blossom-jenkins/-/merge_requests/37/diffs?commit_id=fc7be180bcd6bcfe259566e7261b7e18459de3f3

**Comment by NvTimLiu** [comment] 2021-01-14 15:59
As MR37 got merged, we can close this issue now.

**Closed by NvTimLiu** 2021-01-14 15:59 UTC
Labels: P1, bug
