### ISSUE TITLE
tpc-ds query72 run failed OOM with sf=10000[BUG]

### ISSUE THREAD

**Issue by chenrui17** [NVIDIA/spark-rapids#669] opened 2020-09-04 08:12 UTC
**Describe the bug**
I use yarn cluster with 13 intel 6271 cpu and 13 T4 run TPC-DS, Now they can basically run, but query-72 cannot run success no matter how I tune the configure, I observe the dag and profil its Execution process， I find that it fails in first reduce stage, because first reduce stage is JOIN with 2 big table called store_sales and inventory, I tuned configs like : spark.rapids.sql.concurrentGpuTasks = 1, spark.sql.shufflePartitons=3000, spark.rapids.sql.batchSizeBytes=128m,  but it still OOM on first reduce stage. in addition, i find that this stage join operation will forback to cpu, and use sort merge join , so I set spark.sql.autoBroadcastJoinThreshold =100M , expect to it will transform to broadcastjoin ,but it transform  to GpuSort and GpuShuffleHashJoin operation ,and you know ,it also OOM , What should I do to make query-72 work 
To cpu, even its performance is bad , but it can run successfuly in about 4 minutes

**Steps/Code to reproduce bug**
tpc-ds query-72 10T parquet  data

**Comment by jlowe** [comment] 2020-09-04 15:10
If the CPU performance is also very bad, it would be useful to examine its operation.  Is it spilling extensively even with a large number of shuffle partitions?  If so then there may be extreme data skew causing one or more tasks to receive almost all the data.  The task stats for a stage should reflect whether the shuffle data was spread evenly across the tasks or if most of it went to a small handful of tasks.  Extreme data skew is a known limitation of the current version of the plugin.

**Comment by sameerz** [comment] 2020-09-08 20:40
We need to fix issue #19 and issue #20 to really address this.

**Comment by sameerz** [comment] 2021-02-18 17:53
This is a duplicate of issue #1629 .  We will track the fix there.

**Closed by sameerz** 2021-02-18 17:53 UTC
Labels: bug, duplicate
