### ISSUE TITLE
[BUG] orc_cast_test.py::test_casting_from_overflow_double_to_timestamp[DATAGEN_SEED=1708792552, INJECT_OOM]

### ISSUE THREAD

**Issue by GaryShen2008** [NVIDIA/spark-rapids#10504] opened 2024-02-27 01:53 UTC
**Describe the bug**
```
[2024-02-24T18:20:25.183Z] =================================== FAILURES ===================================

[2024-02-24T18:20:25.183Z] ________________ test_casting_from_overflow_double_to_timestamp ________________

[2024-02-24T18:20:25.183Z] [gw1] linux -- Python 3.9.18 /opt/conda/bin/python

[2024-02-24T18:20:25.183Z] 

[2024-02-24T18:20:25.183Z] spark_tmp_path = '/tmp/pyspark_tests//it-test-334-672-8t6rn-bt653-gw1-1544-1762820611/'

[2024-02-24T18:20:25.183Z] 

[2024-02-24T18:20:25.183Z]     @allow_non_gpu(*non_utc_allow_for_test_casting_from_overflow_long)

[2024-02-24T18:20:25.183Z]     def test_casting_from_overflow_double_to_timestamp(spark_tmp_path):

[2024-02-24T18:20:25.183Z]         orc_path = spark_tmp_path + '/orc_casting_from_overflow_double_to_timestamp'

[2024-02-24T18:20:25.183Z]         with_cpu_session(

[2024-02-24T18:20:25.183Z]             lambda spark: unary_op_df(spark, DoubleGen(min_exp=38)).write.orc(orc_path)

[2024-02-24T18:20:25.183Z]         )

[2024-02-24T18:20:25.183Z] >       assert_gpu_and_cpu_error(

[2024-02-24T18:20:25.183Z]             df_fun=lambda spark: spark.read.schema("a timestamp").orc(orc_path).collect(),

[2024-02-24T18:20:25.183Z]             conf={},

[2024-02-24T18:20:25.183Z]             error_message="ArithmeticException"

[2024-02-24T18:20:25.183Z]         )

[2024-02-24T18:20:25.183Z] 

[2024-02-24T18:20:25.183Z] ../../src/main/python/orc_cast_test.py:137: 

[2024-02-24T18:20:25.183Z] _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

[2024-02-24T18:20:25.183Z] ../../src/main/python/asserts.py:661: in assert_gpu_and_cpu_error

[2024-02-24T18:20:25.183Z]     assert_spark_exception(lambda: with_gpu_session(df_fun, conf), error_message)

[2024-02-24T18:20:25.183Z] _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

[2024-02-24T18:20:25.183Z] 

[2024-02-24T18:20:25.183Z] func = <function assert_gpu_and_cpu_error.<locals>.<lambda> at 0x7f4962870e50>

[2024-02-24T18:20:25.183Z] error_message = 'ArithmeticException'

[2024-02-24T18:20:25.183Z] 

[2024-02-24T18:20:25.183Z]     def assert_spark_exception(func, error_message):

[2024-02-24T18:20:25.183Z]         """

[2024-02-24T18:20:25.183Z]         Assert that a specific Java exception is thrown

[2024-02-24T18:20:25.183Z]         :param func: a function to be verified

[2024-02-24T18:20:25.183Z]         :param error_message: a string such as the one produce by java.lang.Exception.toString

[2024-02-24T18:20:25.183Z]         :return: Assertion failure if no exception matching error_message has occurred.

[2024-02-24T18:20:25.183Z]         """

[2024-02-24T18:20:25.183Z]         with pytest.raises(Exception) as excinfo:

[2024-02-24T18:20:25.183Z] >           func()

[2024-02-24T18:20:25.183Z] E           Failed: DID NOT RAISE <class 'Exception'>

[2024-02-24T18:20:25.183Z] 

[2024-02-24T18:20:25.183Z] ../../src/main/python/asserts.py:647: Failed
```

**Steps/Code to reproduce bug**
Run jenkins/spark-tests.sh with Spark 3.3.4 and the seed.

**Expected behavior**
Test should pass.

**Environment details (please complete the following information)**
 - Environment location: [Standalone]
 - Spark: 3.3.4

**Comment by gerashegalov** [comment] 2024-02-27 05:47
dupe of #10431

**Closed by gerashegalov** 2024-02-27 05:47 UTC
Labels: bug, ? - Needs Triage
