### ISSUE TITLE
[BUG] install build fails with Maven 3.9.3

### ISSUE THREAD

**Issue by jlowe** [NVIDIA/spark-rapids#8685] opened 2023-07-10 14:10 UTC
**Describe the bug**
Trying to do an `install` Maven build when using Maven 3.9.3 fails with the following error:
```
[INFO] --- install:3.1.1:install (default-install) @ rapids-4-spark-sql_2.12 ---
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for RAPIDS Accelerator for Apache Spark Root Project 23.08.0-SNAPSHOT:
[INFO] 
[INFO] RAPIDS Accelerator for Apache Spark Root Project ... SUCCESS [ 14.008 s]
[INFO] RAPIDS Accelerator for Apache Spark SQL Plugin ..... FAILURE [01:50 min]
[INFO] RAPIDS Accelerator for Apache Spark Delta Lake 2.1.x Support SKIPPED
[INFO] RAPIDS Accelerator for Apache Spark Delta Lake 2.2.x Support SKIPPED
[INFO] RAPIDS Accelerator for Apache Spark Shuffle Plugin . SKIPPED
[INFO] RAPIDS Accelerator for Apache Spark Scala UDF Plugin SKIPPED
[INFO] RAPIDS Accelerator for Apache Spark Aggregator ..... SKIPPED
[INFO] RAPIDS Accelerator for Apache Spark Distribution ... SKIPPED
[INFO] rapids-4-spark-integration-tests_2.12 .............. SKIPPED
[INFO] RAPIDS Accelerator for Apache Spark Tests .......... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  02:04 min
[INFO] Finished at: 2023-07-10T09:06:11-05:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-install-plugin:3.1.1:install (default-install) on project rapids-4-spark-sql_2.12: The packaging plugin for this project did not assign a main file to the project but it has attachments. Change packaging to 'pom'. -> [Help 1]
```

**Steps/Code to reproduce bug**
`apache-maven-3.9.3/bin/mvn clean install -DskipTests -Dbuildver=332 -Drat.skip=true`

**Expected behavior**
Build should succeed on the latest stable release of Maven.

**Comment by gerashegalov** [comment] 2023-07-11 20:57
this is probably a duplicate of #8156

**Closed** 2023-07-13 20:55 UTC
Labels: bug, build
