### ISSUE TITLE
[BUG] Add null values back to test_array_intersect for Spark 3.3+ and Databricks 10.4+

### ISSUE THREAD

**Issue by NVnavkumar** [NVIDIA/spark-rapids#6285] opened 2022-08-10 20:03 UTC
**Describe the bug**
Because of the bug described in https://issues.apache.org/jira/browse/SPARK-39976, there is a known issue with array_intersect and NULL values. This causes the integration tests to fail when comparing the CPU version (which has the bug) and the GPU version (which does not have the bug). A workaround (https://github.com/NVIDIA/spark-rapids/pull/6223) was committed which removes null values from array_intersect tests on Spark 3.3+ and Databricks 10.4+.  This is filed to follow up and revert the change made in the workaround when the issue is fixed in Apache Spark and Databricks.

**Comment by tgravescs** [comment] 2022-08-12 14:11
the issue is fixed in 3.3 and master branch, they are working on fixing the other ones.

**Closed** 2022-12-14 00:03 UTC
Labels: bug, spark 3.3+, Spark 3.4+
