### ISSUE TITLE
[BUG] test `json_test.py::test_from_json_struct_decimal` fails

### ISSUE THREAD

**Issue by firestarman** [NVIDIA/spark-rapids#11045] opened 2024-06-12 04:42 UTC
**Describe the bug**
test `json_test.py::test_from_json_struct_decimal` fails in JDK11-nightly.
```
[2024-06-12T02:52:48.271Z]             if (math.isnan(cpu)):
[2024-06-12T02:52:48.271Z]                 assert math.isnan(gpu), "GPU and CPU float values are different at {}".format(path)
[2024-06-12T02:52:48.271Z]             else:
[2024-06-12T02:52:48.271Z]                 assert float_check(cpu, gpu), "GPU and CPU float values are different {}".format(path)
[2024-06-12T02:52:48.271Z]         elif isinstance(cpu, str):
[2024-06-12T02:52:48.271Z]             assert cpu == gpu, "GPU and CPU string values are different at {}".format(path)
[2024-06-12T02:52:48.271Z]         elif isinstance(cpu, datetime):
[2024-06-12T02:52:48.271Z]             assert cpu == gpu, "GPU and CPU timestamp values are different at {}".format(path)
[2024-06-12T02:52:48.271Z]         elif isinstance(cpu, date):
[2024-06-12T02:52:48.271Z]             assert cpu == gpu, "GPU and CPU date values are different at {}".format(path)
[2024-06-12T02:52:48.271Z]         elif isinstance(cpu, bool):
[2024-06-12T02:52:48.271Z]             assert cpu == gpu, "GPU and CPU boolean values are different at {}".format(path)
[2024-06-12T02:52:48.271Z]         elif isinstance(cpu, Decimal):
[2024-06-12T02:52:48.271Z] >           assert cpu == gpu, "GPU and CPU decimal values are different at {}".format(path)
[2024-06-12T02:52:48.271Z] E           AssertionError: GPU and CPU decimal values are different at [1594, 'from_json(a)', 'a']

...
[2024-06-12T02:52:48.273Z] =========================== short test summary info ============================

[2024-06-12T02:52:48.273Z] FAILED ../../src/main/python/json_test.py::test_from_json_struct_decimal[DATAGEN_SEED=1718155923, TZ=UTC] - AssertionError: GPU and CPU decimal values are different at [1594, 'from_json(a)', 'a']

[2024-06-12T02:52:48.273Z] = 1 failed, 26742 passed, 2322 skipped, 698 xfailed, 809 xpassed, 14219 warnings in 4843.71s (1:20:43) =
```

**Expected behavior**
Test should pass.

**Comment by revans2** [comment] 2024-06-12 14:33
@firestarman can you please get the full name of the failing test including the SEED for the datagen? It is likely that datagen generated data that caused the failure instead of just JDK 11 causing it.

**Comment by revans2** [comment] 2024-06-12 14:34
```
../../src/main/python/json_test.py::test_from_json_struct_decimal[DATAGEN_SEED=1718155923, TZ=UTC]
```

**Comment by revans2** [comment] 2024-06-12 14:50
Yup that is it.
```
TEST_PARALLEL=1 DATAGEN_SEED=1718155923 ./run_pyspark_from_build.sh -k 'test_from_json_struct_decimal' -s
```

replicates the failure.

```
--- CPU OUTPUT
+++ GPU OUTPUT
@@ -1592,7 +1592,7 @@
 Row(a='{ "a": "16827.06e+38" }', from_json(a)=Row(a=None))
 Row(a='null', from_json(a)=Row(a=None))
 Row(a='', from_json(a)=None)
-Row(a='{ "a": "0.e86" }', from_json(a)=Row(a=Decimal('0')))
+Row(a='{ "a": "0.e86" }', from_json(a)=Row(a=None))
 Row(a='{ "a": "+4088.13e-33" }', from_json(a)=Row(a=Decimal('0')))
 Row(a='', from_json(a)=None)
 Row(a='{ "a": "+31670.52E-07" }', from_json(a)=Row(a=Decimal('0')))
```

Okay that is really interesting. It looks like the number parsing in `from_json` is different from what it is for regular spark casting.

```
scala> Seq(("0", "{'a': '0'}"), ("100", "{'a': '100'}"), ("0.e86", "{'a': '0.e86'}"), ("0.0e86", "{'a': '0.0e86'}"), ("0e86", "{'a': '0e86'}")).toDF("str", "json").repartition(1).selectExpr("CAST(str as DECIMAL(10,5))", "from_json(json, 'a DECIMAL(10,5)')").show()
+---------+---------------+
|      str|from_json(json)|
+---------+---------------+
|  0.00000|      {0.00000}|
|100.00000|    {100.00000}|
|     null|      {0.00000}|
|     null|      {0.00000}|
|     null|      {0.00000}|
+---------+---------------+
```

I made the assumption that they were the same, and for the most part they should but, but this is an odd corner case that I missed. This happens for both quoted and unquoted numbers. The unquoted numbers are odder because `0.e86` is technically not in the proper JSON number format and is invalid for Spark, but the problem shows up for `0e86` and `0.0e86` too.

**Comment by revans2** [comment] 2024-06-12 16:15
This also appears to be a dupe of https://github.com/NVIDIA/spark-rapids/issues/11045

**Comment by firestarman** [comment] 2024-06-13 01:21
> @firestarman can you please get the full name of the failing test including the SEED for the datagen? It is likely that datagen generated data that caused the failure instead of just JDK 11 causing it

Done

**Comment by firestarman** [comment] 2024-06-13 01:23
>This also appears to be a dupe of https://github.com/NVIDIA/spark-rapids/issues/11045

Typo? This is #11045.

**Comment by revans2** [comment] 2024-06-13 16:46
Yup should have been a dupe of https://github.com/NVIDIA/spark-rapids/issues/10898

**Closed** 2024-06-18 20:10 UTC
Labels: bug, ? - Needs Triage
