### ISSUE TITLE
[FEA] Support percentile function

### ISSUE THREAD

**Issue by nvliyuan** [NVIDIA/spark-rapids#8513] opened 2023-06-06 07:30 UTC
It would be better to support [percentile](https://spark.apache.org/docs/latest/api/sql/index.html#percentile) function:
Codes:
```
spark.sql("SELECT percentile(col, 0.3) FROM VALUES (0), (10) AS tab(col)").show
```
driverlogs:
```
! <Percentile> percentile(col#28, 0.3, 1, 0, 0) cannot run on GPU because GPU does not currently support the operator class org.apache.spark.sql.catalyst.expressions.aggregate.Percentile
```

**Comment by mattahrens** [comment] 2023-06-06 20:38
Duplicate of https://github.com/NVIDIA/spark-rapids/issues/6266

**Closed by mattahrens** 2023-06-06 20:38 UTC
Labels: duplicate, feature request
