### ISSUE TITLE
[BUG] test_broadcast_nested_loop_join_special_case fails on databricks

### ISSUE THREAD

**Issue by tgravescs** [NVIDIA/spark-rapids#427] opened 2020-07-24 20:52 UTC
The test_broadcast_nested_loop_join_special_case test has been failing on databricks.  see https://ci.ngcc.nvidia.com/job/spark/job/rapids_databricks_nightly-0.2-github/41/console

14:15:10  FAILED src/main/python/join_test.py::test_broadcast_nested_loop_join_special_case[String][IGNORE_ORDER({'local': True})]
14:15:10  FAILED src/main/python/join_test.py::test_broadcast_nested_loop_join_special_case[Byte][IGNORE_ORDER({'local': True})]
14:15:10  FAILED src/main/python/join_test.py::test_broadcast_nested_loop_join_special_case[Short][IGNORE_ORDER({'local': True})]
14:15:10  FAILED src/main/python/join_test.py::test_broadcast_nested_loop_join_special_case[Integer][IGNORE_ORDER({'local': True})]
14:15:10  FAILED src/main/python/join_test.py::test_broadcast_nested_loop_join_special_case[Long][IGNORE_ORDER({'local': True})]
14:15:10  FAILED src/main/python/join_test.py::test_broadcast_nested_loop_join_special_case[Boolean][IGNORE_ORDER({'local': True})]
14:15:10  FAILED src/main/python/join_test.py::test_broadcast_nested_loop_join_special_case[Date][IGNORE_ORDER({'local': True})]
14:15:10  FAILED src/main/python/join_test.py::test_broadcast_nested_loop_join_special_case[Timestamp][IGNORE_ORDER({'local': True})]
14:15:10  FAILED src/main/python/join_test.py::test_broadcast_nested_loop_join_special_case[Float][IGNORE_ORDER({'local': True}), INCOMPAT]
14:15:10  FAILED src/main/python/join_test.py::test_broadcast_nested_loop_join_special_case[Double][IGNORE_ORDER({'local': True}), INCOMPAT]

need to investigate what is failing. In the mean time I may xfail them.

**Comment by revans2** [comment] 2020-07-30 20:26
This is a duplicate of #441

**Closed by revans2** 2020-07-30 20:26 UTC
Labels: bug
