### ISSUE TITLE
[BUG] dynamic partition pruning filter pushdown emr 6.2 doesn't appear to work with parquet reader

### ISSUE THREAD

**Issue by tgravescs** [NVIDIA/spark-rapids#1386] opened 2020-12-14 15:15 UTC
**Describe the bug**
Running on emr 6.2 we noticed that tpcds query 38 was reading more files on Gpu then cpu. Note this was running with the 0.2 rapids plugin release.  turning off dynamic partition pruning on cpu results in same number of files on cpu.  Looking at the plan it looks like the dynamicpruningexpression on the gpu is set to true vs the actualy column name:

```
cpu:
                                                                    :                 :        +- FileScan parquet tpcds_sf3000_withdecimal_withdate_withnulls.web_sales[ws_bill_customer_sk#107,ws_sold_date_sk#137] Batched: true, DataFilters: [isnotnull(ws_bill_customer_sk#107)], Format: Parquet, Location: InMemoryFileIndex[s3://tpcds-kr/tpcds-3tb/sf3000-parquet/useDecimal=true,useDate=true,filterNull=..., PartitionFilters: [isnotnull(ws_sold_date_sk#137), dynamicpruningexpression(ws_sold_date_sk#137 IN dynamicpruning#2..., PushedFilters: [IsNotNull(ws_bill_customer_sk)], ReadSchema: struct<ws_bill_customer_sk:int>
 
 gpu:
                                                                     :           :        +- GpuFileGpuScan parquet tpcds_sf3000_withdecimal_withdate_withnulls.web_sales[ws_bill_customer_sk#107,ws_sold_date_sk#137] Batched: true, DataFilters: [isnotnull(ws_bill_customer_sk#107)], Format: Parquet, Location: InMemoryFileIndex[s3://tpcds-kr/tpcds-3tb/sf3000-parquet/useDecimal=true,useDate=true,filterNull=..., PartitionFilters: [isnotnull(ws_sold_date_sk#137), dynamicpruningexpression(true)], PushedFilters: [IsNotNull(ws_bill_customer_sk)], ReadSchema: struct<ws_bill_customer_sk:int>
 
```

investigate why we are reading 3 times the files on gpu side.

**Comment by tgravescs** [comment] 2020-12-14 15:21
trying this on yarn with latest 0.3 it appears that the pruning expression is there on gpu and number of files and rows read is same as cpu. The files on the yarn cluster are partitioned but I'm not sure if exactly the same. I am using smaller dataset.

 ```
 +- GpuFileGpuScan parquet [ws_bill_customer_sk#219,ws_sold_date_sk#249] Batched: true, DataFilters: [isnotnull(ws_bill_customer_sk#219)], Format: Parquet, Location: InMemoryFileIndex[hdfs://host:8020/data/spark_etl_tpcds_10g_partitioned_parquet/web_sales..., PartitionFilters: [isnotnull(ws_sold_date_sk#249), dynamicpruningexpression(ws_sold_date_sk#249 IN dynamicpruning#9..., PushedFilters: [IsNotNull(ws_bill_customer_sk)], ReadSchema: struct<ws_bill_customer_sk:int>
                                                                              :     :         
```

I verified that turning off DPP results in both cpu and gpu reading a lot more partitions.  So I need to see if this is a 0.2 issue or an EMR issue.

**Comment by tgravescs** [comment] 2020-12-14 15:32
I don't see this issue on yarn with the 0.2 plugin jar either, need to test on emr more.

**Comment by sameerz** [comment] 2020-12-15 21:18
Duplicate of #1378

**Closed** 2020-12-15 21:18 UTC
Labels: bug, duplicate
