### ISSUE TITLE
[Audit][FEA][SPARK-36778] Accelerate case-insenstive ILIKE

### ISSUE THREAD

**Issue by gerashegalov** [NVIDIA/spark-rapids#4143] opened 2021-11-18 08:15 UTC
SPARK-36774 introduces ILIKE, and SPARK-36778 makes it available in the Scala DF API.
It should be available on GPU.

**Comment by jlowe** [comment] 2024-02-28 21:24
Duplicate of #3956

**Closed by jlowe** 2024-02-28 21:24 UTC
Labels: duplicate, audit_3.3.0
