### ISSUE TITLE
[BUG] regexp: ast fuzz tests with unicode fail in CI but pass locally

### ISSUE THREAD

**Issue by andygrove** [NVIDIA/spark-rapids#5549] opened 2022-05-19 20:36 UTC
**Describe the bug**
The new ast fuzz tests with unicode inputrs added in https://github.com/NVIDIA/spark-rapids/pull/5573  fail in CI but pass locally

**Steps/Code to reproduce bug**
Run these `RegularExpressionTranspilerSuite` tests in CI:

```
  test("AST fuzz test - regexp_find - full unicode input") {
    doAstFuzzTest(None, REGEXP_LIMITED_CHARS_FIND,
      RegexFindMode)
  }

  test("AST fuzz test - regexp_replace - full unicode input") {
    doAstFuzzTest(None, REGEXP_LIMITED_CHARS_REPLACE,
      RegexReplaceMode)
  }
```

**Expected behavior**
Should have same behavior locally and in CI

**Environment details (please complete the following information)**
N/A

**Additional context**
N/A

**Comment by andygrove** [comment] 2022-06-02 16:11
We documented this issue in 22.06

**Comment by andygrove** [comment] 2022-06-02 16:11
We need changes to CI to be able to complete this issue

**Comment by NVnavkumar** [comment] 2022-06-18 00:17
Duplicate of #5629

**Closed by NVnavkumar** 2022-06-18 00:17 UTC
Labels: bug, P1
