### ISSUE TITLE
[BUG] test failures in CI build (observed in UCX job) after starting to use 21.08

### ISSUE THREAD

**Issue by abellina** [NVIDIA/spark-rapids#2723] opened 2021-06-16 12:51 UTC
These tests failed:

- test_broadcast_nested_loop_join
- test_broadcast_nested_loop_join_special_case_count
- test_cartesean_join
- test_cartesean_join_special_case_count
- test_cartesean_join_special_case_group_by

With basic types as well as nested types. The job was changed for last night's run to use 21.08. I had updated it to use UCX 1.11 native libraries and ran successfully earlier.

---

UPDATE:

https://github.com/NVIDIA/spark-rapids/pull/2749 was PRed to revert a change introduced in https://github.com/NVIDIA/spark-rapids/pull/2702 that recently enabled these types in the plugin and the integration tests that failed above. 

The condition for this issue (#2723) to be closed is that @revans2's code should be re-added and tests should pass.

**Comment by abellina** [comment] 2021-06-16 12:51
I am not sure if this is UCX specific or not.

**Comment by abellina** [comment] 2021-06-16 12:53
Here's one example of an exception:
```
../../src/main/python/join_test.py::test_broadcast_nested_loop_join[100-String][IGNORE_ORDER({'local': True})] 21/06/16 09:18:56 WARN TaskSetManager: Lost task 1.0 in stage 28146.0 (TID 1147491) (10.136.6.4 executor 3): ai.rapids.cudf.CudaException: an illegal memory access was encountered
  at ai.rapids.cudf.Cuda.memcpyOnStream(Native Method)
  at ai.rapids.cudf.Cuda.memcpy(Cuda.java:472)
  at ai.rapids.cudf.Cuda.memcpy(Cuda.java:288)
  at ai.rapids.cudf.BaseDeviceMemoryBuffer.copyFromHostBuffer(BaseDeviceMemoryBuffer.java:43)
  at ai.rapids.cudf.BaseDeviceMemoryBuffer.copyFromHostBuffer(BaseDeviceMemoryBuffer.java:105)
  at ai.rapids.cudf.HostColumnVector.copyToDevice(HostColumnVector.java:198)
  at ai.rapids.cudf.HostColumnVector$ColumnBuilder.buildAndPutOnDevice(HostColumnVector.java:1268)
  at com.nvidia.spark.rapids.GpuColumnVector$GpuColumnarBatchBuilder.buildAndPutOnDevice(GpuColumnVector.java:400)
  at com.nvidia.spark.rapids.GpuColumnVector$GpuColumnarBatchBuilderBase.build(GpuColumnVector.java:275)
  at com.nvidia.spark.rapids.RowToColumnarIterator.$anonfun$buildBatch$2(GpuRowToColumnarExec.scala:613)
  at com.nvidia.spark.rapids.Arm.withResource(Arm.scala:28)
  at com.nvidia.spark.rapids.Arm.withResource$(Arm.scala:26)
  at com.nvidia.spark.rapids.RowToColumnarIterator.withResource(GpuRowToColumnarExec.scala:549)
  at com.nvidia.spark.rapids.RowToColumnarIterator.buildBatch(GpuRowToColumnarExec.scala:612)
  at com.nvidia.spark.rapids.RowToColumnarIterator.next(GpuRowToColumnarExec.scala:570)
  at com.nvidia.spark.rapids.RowToColumnarIterator.next(GpuRowToColumnarExec.scala:549)
  at scala.collection.Iterator$$anon$10.next(Iterator.scala:459)
  at scala.collection.Iterator$$anon$10.next(Iterator.scala:459)
  at scala.collection.Iterator.foreach(Iterator.scala:941)
  at scala.collection.Iterator.foreach$(Iterator.scala:941)
  at scala.collection.AbstractIterator.foreach(Iterator.scala:1429)
  at scala.collection.generic.Growable.$plus$plus$eq(Growable.scala:62)
  at scala.collection.generic.Growable.$plus$plus$eq$(Growable.scala:53)
  at scala.collection.mutable.ArrayBuffer.$plus$plus$eq(ArrayBuffer.scala:105)
  at scala.collection.mutable.ArrayBuffer.$plus$plus$eq(ArrayBuffer.scala:49)
  at scala.collection.TraversableOnce.to(TraversableOnce.scala:315)
  at scala.collection.TraversableOnce.to$(TraversableOnce.scala:313)
  at scala.collection.AbstractIterator.to(Iterator.scala:1429)
  at scala.collection.TraversableOnce.toBuffer(TraversableOnce.scala:307)
  at scala.collection.TraversableOnce.toBuffer$(TraversableOnce.scala:307)
  at scala.collection.AbstractIterator.toBuffer(Iterator.scala:1429)
  at scala.collection.TraversableOnce.toArray(TraversableOnce.scala:294)
  at scala.collection.TraversableOnce.toArray$(TraversableOnce.scala:288)
  at scala.collection.AbstractIterator.toArray(Iterator.scala:1429)
  at org.apache.spark.rdd.RDD.$anonfun$collect$2(RDD.scala:1030)
  at org.apache.spark.SparkContext.$anonfun$runJob$5(SparkContext.scala:2236)
  at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:90)
  at org.apache.spark.scheduler.Task.run(Task.scala:131)
  at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$3(Executor.scala:497)
  at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1439)
  at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:500)
  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
  at java.lang.Thread.run(Thread.java:748)
```

**Comment by abellina** [comment] 2021-06-16 13:08
`test_cartesian_join` seems to have a row to columnar followed by a columnar to row...

Seems orthogonal, but pointing it out.

```
at com.nvidia.spark.rapids.RowToColumnarIterator.next(GpuRowToColumnarExec.scala:549)
at scala.collection.Iterator$$anon$10.next(Iterator.scala:459)
at scala.collection.Iterator$$anon$11.nextCur(Iterator.scala:484)
at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:490)
at com.nvidia.spark.rapids.ColumnarToRowIterator.$anonfun$fetchNextBatch$2(GpuColumnarToRowExec.scala:222)
```

**Comment by abellina** [comment] 2021-06-16 13:30
This is the best kind of failure, it actually failed again by just running the cartesian join tests. **No shuffle involved**:

```
== Physical Plan ==
GpuColumnarToRow (7)
+- GpuCartesianProduct (6)
   :- GpuRowToColumnar (2)
   :  +- * Scan ExistingRDD (1)
   +- GpuProject (5)
      +- GpuRowToColumnar (4)
         +- * Scan ExistingRDD (3)
```

First failure was `Array(String)`, other types succeeded (basic types, and basic type arrays). Something with nested types?

```
08:22:58  ../../src/main/python/join_test.py::test_cartesean_join[100-Array(Double)][IGNORE_ORDER({'local': True})] [32mPASSED[0m[32m [ 13%][0m
08:23:06  ../../src/main/python/join_test.py::test_cartesean_join[100-Array(String)][IGNORE_ORDER({'local': True})] 21/06/16 13:23:05 WARN TaskSetManager: Lost task 1996.0 in stage 45.0 (TID 105676) (10.136.6.4 executor 1): ai.rapids.cudf.CudaException: misaligned address
```

**Comment by abellina** [comment] 2021-06-16 14:41
At this point, I've confirmed that disabling the `String` variant of a couple of these tests cases makes the test pass.

**Comment by abellina** [comment] 2021-06-16 21:50
Ok built a cudf without this diff: https://github.com/rapidsai/cudf/commit/2ce0835212759a0e2f3efbce34759d5308bf3e40. And the tests pass in the same build. Working with @hyperbolic2346 on trying to understand why.

**Comment by abellina** [comment] 2021-06-18 14:07
Related to: https://github.com/NVIDIA/spark-rapids/pull/2702

**Comment by abellina** [comment] 2021-06-18 14:14
> Ok built a cudf without this diff: rapidsai/cudf@2ce0835. And the tests pass in the same build. Working with @hyperbolic2346 on trying to understand why.

This was a red herring. Just updating the issue. It seems that these tests were recently enabled 7 days ago in the plugin, so I am not 100% sure when it started breaking at this point.

**Comment by abellina** [comment] 2021-06-21 14:19
Before closing this issue, ensure that the reverted code (#2702) was re-added and passes tests.

**Comment by sameerz** [comment] 2021-06-22 20:56
@abellina were you able to get a repro case for this failure?

**Comment by abellina** [comment] 2021-06-22 21:05
> @abellina were you able to get a repro case for this failure?
Not yet.

**Comment by abellina** [comment] 2021-06-29 16:26
I verified that with the latest jars as of Monday (yesterday) we still see this issue with this diff: https://github.com/NVIDIA/spark-rapids/pull/2702. No root cause yet.

**Comment by mythrocks** [comment] 2021-07-07 17:43
I suspect this has something to do with `contiguous_split()` with an `Array<String>` payload. The `cartesean_join` tests run correctly if `Array<String>` is skipped. 

I'm trying to narrow it down now.

**Comment by mythrocks** [comment] 2021-07-08 05:22
Persisting both sides of the `CROSS JOIN` into separate files and then performing the join does not reproduce the problem. :/

Hitting it with `cuda-memcheck` now.

**Comment by mythrocks** [comment] 2021-07-20 20:47
It's been a while since I updated. I traced this to a bad read, in the case of nested lists. This should be sorted out once rapidsai/cudf#8791 is committed.
I have verified that the failing tests from the description all pass with the changes in rapidsai/cudf#8791.

**Closed** 2021-07-26 19:07 UTC
Labels: P1, bug, cudf_dependency
