### ISSUE TITLE
[BUG] GpuJsonToStructs runs OOM even with very small partition/batch

### ISSUE THREAD

**Issue by viadea** [NVIDIA/spark-rapids#6481] opened 2022-09-01 20:57 UTC
GpuJsonToStructs runs OOM even with very small partition/batch.

**Env:**
Azure Databricks
Server type: Standard_NC8as_T4_v3
rapids_4_spark_2_12_22_10_0_20220821_120604_13.jar

Even after reducing:
```
spark.conf.set('spark.rapids.sql.batchSizeBytes', '100K')
spark.conf.set('spark.rapids.sql.reader.batchSizeBytes', '100K')
spark.conf.set('spark.sql.files.maxPartitionBytes', '100K')
```
The job still failed with OOM:
```
java.lang.OutOfMemoryError: Could not allocate native memory: std::bad_alloc: out_of_memory: RMM failure at:/home/jenkins/agent/workspace/jenkins-spark-rapids-jni_nightly-dev-193-cuda11/thirdparty/cudf/cpp/build/_deps/rmm-src/include/rmm/mr/device/arena_memory_resource.hpp:159: Maximum pool size exceeded
	at ai.rapids.cudf.ColumnVector.makeList(Native Method)
	at ai.rapids.cudf.ColumnVector.makeList(ColumnVector.java:458)
	at org.apache.spark.sql.rapids.GpuJsonToStructs.$anonfun$makeMap$5(GpuJsonToStructs.scala:92)
	at com.nvidia.spark.rapids.Arm.withResource(Arm.scala:46)
	at com.nvidia.spark.rapids.Arm.withResource$(Arm.scala:44)
	at com.nvidia.spark.rapids.GpuUnaryExpression.withResource(GpuExpressions.scala:186)
	at org.apache.spark.sql.rapids.GpuJsonToStructs.$anonfun$makeMap$3(GpuJsonToStructs.scala:91)
	at com.nvidia.spark.rapids.Arm.withResource(Arm.scala:46)
	at com.nvidia.spark.rapids.Arm.withResource$(Arm.scala:44)
	at com.nvidia.spark.rapids.GpuUnaryExpression.withResource(GpuExpressions.scala:186)
	at org.apache.spark.sql.rapids.GpuJsonToStructs.makeMap(GpuJsonToStructs.scala:87)
	at org.apache.spark.sql.rapids.GpuJsonToStructs.$anonfun$doColumnar$6(GpuJsonToStructs.scala:141)
	at com.nvidia.spark.rapids.Arm.withResource(Arm.scala:46)
	at com.nvidia.spark.rapids.Arm.withResource$(Arm.scala:44)
	at com.nvidia.spark.rapids.GpuUnaryExpression.withResource(GpuExpressions.scala:186)
	at org.apache.spark.sql.rapids.GpuJsonToStructs.$anonfun$doColumnar$1(GpuJsonToStructs.scala:140)
	at com.nvidia.spark.rapids.Arm.withResource(Arm.scala:28)
	at com.nvidia.spark.rapids.Arm.withResource$(Arm.scala:26)
	at com.nvidia.spark.rapids.GpuUnaryExpression.withResource(GpuExpressions.scala:186)
	at org.apache.spark.sql.rapids.GpuJsonToStructs.doColumnar(GpuJsonToStructs.scala:105)
	at com.nvidia.spark.rapids.GpuUnaryExpression.doItColumnar(GpuExpressions.scala:192)
	at com.nvidia.spark.rapids.GpuUnaryExpression.$anonfun$columnarEval$1(GpuExpressions.scala:203)
	at com.nvidia.spark.rapids.Arm.withResource(Arm.scala:28)
	at com.nvidia.spark.rapids.Arm.withResource$(Arm.scala:26)
	at com.nvidia.spark.rapids.GpuUnaryExpression.withResource(GpuExpressions.scala:186)
	at com.nvidia.spark.rapids.GpuUnaryExpression.columnarEval(GpuExpressions.scala:202)
	at com.nvidia.spark.rapids.RapidsPluginImplicits$ReallyAGpuExpression.columnarEval(implicits.scala:34)
	at com.nvidia.spark.rapids.GpuBinaryExpression.columnarEval(GpuExpressions.scala:252)
	at com.nvidia.spark.rapids.GpuBinaryExpression.columnarEval$(GpuExpressions.scala:251)
	at org.apache.spark.sql.rapids.GpuGetMapValue.columnarEval(complexTypeExtractors.scala:190)
	at com.nvidia.spark.rapids.RapidsPluginImplicits$ReallyAGpuExpression.columnarEval(implicits.scala:34)
	at com.nvidia.spark.rapids.GpuExpressionsUtils$.columnarEvalToColumn(GpuExpressions.scala:93)
	at com.nvidia.spark.rapids.GpuUnaryExpression.columnarEval(GpuExpressions.scala:202)
	at com.nvidia.spark.rapids.RapidsPluginImplicits$ReallyAGpuExpression.columnarEval(implicits.scala:34)
	at com.nvidia.spark.rapids.GpuExpressionsUtils$.columnarEvalToColumn(GpuExpressions.scala:93)
	at com.nvidia.spark.rapids.GpuProjectExec$.projectSingle(basicPhysicalOperators.scala:102)
	at com.nvidia.spark.rapids.GpuFilter$.$anonfun$apply$2(basicPhysicalOperators.scala:288)
	at com.nvidia.spark.rapids.Arm.withResource(Arm.scala:28)
	at com.nvidia.spark.rapids.Arm.withResource$(Arm.scala:26)
	at com.nvidia.spark.rapids.GpuFilter$.withResource(basicPhysicalOperators.scala:259)
	at com.nvidia.spark.rapids.GpuFilter$.apply(basicPhysicalOperators.scala:286)
	at com.nvidia.spark.rapids.GpuFilter$.$anonfun$apply$1(basicPhysicalOperators.scala:267)
	at com.nvidia.spark.rapids.Arm.withResource(Arm.scala:28)
	at com.nvidia.spark.rapids.Arm.withResource$(Arm.scala:26)
	at com.nvidia.spark.rapids.GpuFilter$.withResource(basicPhysicalOperators.scala:259)
	at com.nvidia.spark.rapids.GpuFilter$.apply(basicPhysicalOperators.scala:266)
	at com.nvidia.spark.rapids.GpuFilterExec.$anonfun$doExecuteColumnar$4(basicPhysicalOperators.scala:364)
	at scala.collection.Iterator$$anon$10.next(Iterator.scala:461)
	at com.nvidia.spark.rapids.CollectTimeIterator.$anonfun$next$1(GpuExec.scala:199)
	at com.nvidia.spark.rapids.Arm.withResource(Arm.scala:28)
	at com.nvidia.spark.rapids.Arm.withResource$(Arm.scala:26)
	at com.nvidia.spark.RebaseHelper$.withResource(RebaseHelper.scala:26)
	at com.nvidia.spark.rapids.CollectTimeIterator.next(GpuExec.scala:198)
	at com.nvidia.spark.rapids.AbstractGpuCoalesceIterator.hasNext(GpuCoalesceBatches.scala:289)
	at scala.collection.Iterator$$anon$10.hasNext(Iterator.scala:460)
	at com.nvidia.spark.rapids.GpuHashAggregateIterator.$anonfun$next$2(aggregate.scala:237)
	at scala.Option.getOrElse(Option.scala:189)
	at com.nvidia.spark.rapids.GpuHashAggregateIterator.next(aggregate.scala:235)
	at com.nvidia.spark.rapids.GpuHashAggregateIterator.next(aggregate.scala:181)
	at 
```

Waiting for sample data to repro.

**Comment by viadea** [comment] 2022-09-02 19:52
When this issue happened, some other tasks failed with below stacktrace together with above OOM errors:

**Comment by viadea** [comment] 2022-09-02 22:19
Found that the problematic parquet file's biggest column's row group size is around 800M(uncompressed):
```
>>> parquet_file.metadata.row_group(0).column(1)
  total_compressed_size: 1xxxxxxxx
  total_uncompressed_size: 8xxxxxxxx
```

If I recreated the parquet file, then the row group's uncompressed size dropped to just 70M:
```
  total_compressed_size: 1xxxxxxx
  total_uncompressed_size: 7xxxxxxx
```
After that, the query works fine.

**Comment by revans2** [comment] 2022-09-06 18:25
I also was able to reproduce the issue with the provided data. There is also a huge explosion in the amount of memory used because the columns are very sparse. I was able to put together a patch to avoid that, but the performance cost right now is not worth it. I am inclined to remove support for GpuJsonToStructs until we can get better support from cudf for this type of use case. The overhead of hacking around things to make this work appears to be really very high.

**Comment by sameerz** [comment] 2022-09-07 20:23
`from_json` was reverted in https://github.com/NVIDIA/spark-rapids/pull/6510.  We need to revisit the implementation.  Closing this as wontfix.

**Closed by sameerz** 2022-09-07 20:23 UTC
Labels: bug, ? - Needs Triage

**Comment by viadea** [comment] 2024-08-02 18:08
The recent error for the same user query is now in 24.08:
```
ai.rapids.cudf.CudfException: CUDF failure at:/home/jenkins/agent/workspace/jenkins-spark-rapids-jni_nightly-dev-819-cuda11/src/main/cpp/src/map_utils.cu:149: JSON Parser encountered an invalid format at location 197291503
	at com.nvidia.spark.rapids.jni.MapUtils.extractRawMapFromJsonString(Native Method)
	at com.nvidia.spark.rapids.jni.MapUtils.extractRawMapFromJsonString(MapUtils.java:49)
	at org.apache.spark.sql.rapids.GpuJsonToStructs.doColumnar(GpuJsonToStructs.scala:168)
	at com.nvidia.spark.rapids.GpuUnaryExpression.doItColumnar(GpuExpressions.scala:250)
	at com.nvidia.spark.rapids.GpuUnaryExpression.$anonfun$columnarEval$1(GpuExpressions.scala:261)
	at com.nvidia.spark.rapids.Arm$.withResource(Arm.scala:30)
	at com.nvidia.spark.rapids.GpuUnaryExpression.columnarEval(GpuExpressions.scala:260)
	at com.nvidia.spark.rapids.GpuExpression.columnarEvalAny(GpuExpressions.scala:144)
	at com.nvidia.spark.rapids.GpuExpression.columnarEvalAny$(GpuExpressions.scala:144)
	at com.nvidia.spark.rapids.GpuUnaryExpression.columnarEvalAny(GpuExpressions.scala:244)
	at com.nvidia.spark.rapids.RapidsPluginImplicits$ReallyAGpuExpression.columnarEvalAny(implicits.scala:39)
	at com.nvidia.spark.rapids.GpuBinaryExpression.columnarEval(GpuExpressions.scala:310)
	at com.nvidia.spark.rapids.GpuBinaryExpression.columnarEval$(GpuExpressions.scala:309)
	at org.apache.spark.sql.rapids.GpuGetMapValue.columnarEval(complexTypeExtractors.scala:202)
	at com.nvidia.spark.rapids.GpuExpression.columnarEvalAny(GpuExpressions.scala:144)
	at com.nvidia.spark.rapids.GpuExpression.columnarEvalAny$(GpuExpressions.scala:144)
	at org.apache.spark.sql.rapids.GpuGetMapValue.columnarEvalAny(complexTypeExtractors.scala:202)
	at com.nvidia.spark.rapids.RapidsPluginImplicits$ReallyAGpuExpression.columnarEvalAny(implicits.scala:39)
	at com.nvidia.spark.rapids.GpuBinaryExpression.columnarEval(GpuExpressions.scala:310)
	at com.nvidia.spark.rapids.GpuBinaryExpression.columnarEval$(GpuExpressions.scala:309)
	at com.nvidia.spark.rapids.CudfBinaryOperator.columnarEval(GpuExpressions.scala:417)
	at com.nvidia.spark.rapids.GpuExpression.columnarEvalAny(GpuExpressions.scala:144)
```
