### ISSUE TITLE
[BUG]window operation crashing with OOM

### ISSUE THREAD

**Issue by nvliyuan** [NVIDIA/spark-rapids#3716] opened 2021-09-30 06:34 UTC
**Describe the bug**
the job will crash with OOM error while running one 3TB dataset, but works well on 1TB.

```
21/09/30 02:43:33 WARN org.apache.spark.scheduler.TaskSetManager: Lost task 42.0 in stage 21.0 (TID 1550) (XXXX.c.rapids-spark.internal executor 8): java.lang.OutOfMemoryError: Could not allocate native memory: std::bad_alloc: RMM failure at:/home/jenkins/agent/workspace/jenkins-cudf_nightly-pre_release-github-85-cuda11/cpp/build/_deps/rmm-src/include/rmm/mr/device/arena_memory_resource.hpp:157: Maximum pool size exceeded
	at ai.rapids.cudf.Table.concatenate(Native Method)
	at ai.rapids.cudf.Table.concatenate(Table.java:1391)
	at com.nvidia.spark.rapids.GpuKeyBatchingIterator.$anonfun$concatPending$2(GpuKeyBatchingIterator.scala:140)
	at com.nvidia.spark.rapids.Arm.withResource(Arm.scala:64)
	at com.nvidia.spark.rapids.Arm.withResource$(Arm.scala:62)
	at com.nvidia.spark.rapids.GpuKeyBatchingIterator.withResource(GpuKeyBatchingIterator.scala:35)
	at com.nvidia.spark.rapids.GpuKeyBatchingIterator.$anonfun$concatPending$1(GpuKeyBatchingIterator.scala:125)
	at com.nvidia.spark.rapids.Arm.withResource(Arm.scala:28)
```
**Steps/Code to reproduce bug**
**Environment details (please complete the following information)**
server: GCP
master-machine-type n1-standard-4
worker-machine-type n1-standard-16  with 2 T4 GPU per node
CUDF_JAR = "/XXXX/**cudf-21.10.0-20210928.121813-62.jar"**
RAPIDS_JAR = "/XXXX/**rapids-4-spark_2.12-21.10.0-20210928.181339-115.jar"**
```
conf.setMaster("yarn")
conf.setAppName("XXX")
conf.set("spark.executor.instances","8")
conf.set("spark.executor.cores", "6") 
conf.set("spark.driver.memory", "10g")
conf.set("spark.driver.cores", "4")
conf.set("spark.executor.memory", "8g")

conf.set("spark.locality.wait", "0")
conf.set("spark.sql.files.maxPartitionBytes", "512m")
conf.set("spark.rapids.sql.reader.batchSizeBytes","512m")
conf.set("spark.dynamicAllocation.enabled", "false") 
conf.set("spark.sql.adaptive.enabled", "true") 

conf.set("spark.executor.resource.gpu.amount", "1")
conf.set("spark.rapids.sql.concurrentGpuTasks", "1")
conf.set("spark.rapids.memory.pinnedPool.size", "4G")
conf.set("spark.task.resource.gpu.amount", "0.16")
conf.set("spark.rapids.sql.enabled", "true") 
conf.set("spark.plugins", "com.nvidia.spark.SQLPlugin")
conf.set("spark.rapids.sql.variableFloatAgg.enabled", "true")
conf.set("spark.driver.extraClassPath", CUDF_JAR + ":" + RAPIDS_JAR)
conf.set("spark.executor.extraClassPath", CUDF_JAR + ":" + RAPIDS_JAR)
conf.set("spark.jars", CUDF_JAR + "," + RAPIDS_JAR)

spark.read.parquet("gs://XXXXXX/3tb/tpcds-3TB-parquet/store_sales.dat").createOrReplaceTempView("store_sales")

query = '''
select ss_customer_sk,avg(avg_price) as avg_price
from
(
SELECT ss_customer_sk ,avg(ss_sales_price) OVER (PARTITION BY ss_customer_sk order by ss_sold_date_sk ROWS BETWEEN 10 PRECEDING AND 10 FOLLOWING ) as avg_price
FROM store_sales
) group by ss_customer_sk order by 2 desc 
'''
```
**Additional context**
The plugin should handle large window operations without crashing since v21.08, not sure why the error happens.

**Comment by revans2** [comment] 2021-09-30 16:19
This is a known issue. #1860 would be how we can fix this.  Essentially right now to work we need to hold all of the data for a single `ss_customer_sk` in gpu memory. As the scale factor increases so does the maximum amount of data for a single customer.  There are ways to fix it for this one case.

> The plugin should handle large window operations without crashing since v21.08, not sure why the error happens.

Are you saying that this test passes in 21.08, but not in 21.10?

**Comment by nvliyuan** [comment] 2021-09-30 16:33
No, I thought the new feature out of core windowing of v21.08 would avoid this issue. 

> Are you saying that this test passes in 21.08, but not in 21.10?

**Comment by revans2** [comment] 2021-09-30 16:39
Out of core windowing did not get 100% done. #1789 is the feature to finish out of core windowing, and it is lacking #1860, which we could do now, but are low on time to finish with everything else happening. It is also missing a similar feature for range based queries, but would require help from cudf to do that efficiently.  There are even further optimizations that we could do past that. It just depends on customer need and asks.

**Comment by nvliyuan** [comment] 2021-09-30 16:44
I got it, thanks for the explanation.

**Comment by sameerz** [comment] 2021-10-05 20:43
Closing based on the fact that we need to complete #1789 and #1860, and this is in a sense a duplicate of those.

**Closed by sameerz** 2021-10-05 20:43 UTC
Labels: bug
