### ISSUE TITLE
[BUG] cufile.log is being emitted

### ISSUE THREAD

**Issue by jlowe** [NVIDIA/spark-rapids#4404] opened 2021-12-20 23:12 UTC
Related to #4397, a new `cufile.log` seems to be appearing during the build, probably as a side-effect of testing.  We need to ensure this file is not being emitted in a production environment and ideally stops being emitted during the build/tests.

**Comment by firestarman** [comment] 2021-12-22 01:21
This is related to https://docs.nvidia.com/gpudirect-storage/api-reference-guide/index.html#json-config-file, seems no option is provided to disable this log.

**Comment by GaryShen2008** [comment] 2021-12-22 02:29
Assign to Andy, since he has already created a PR to fix this.

**Comment by jlowe** [comment] 2021-12-22 15:04
> Assign to Andy, since he has already created a PR to fix this.

There's just a PR to ignore the file, not prevent it from appearing, correct?  We need to prevent this file from being emitted in the first place if it is being created in regular use.

**Comment by GaryShen2008** [comment] 2021-12-23 00:29
According to https://github.com/NVIDIA/spark-rapids/issues/4404#issuecomment-999208742, the log is generated by cuFile. There's no API to stop the log. Are we able to stop it in plugin side or we just figure out why it's generated?

**Comment by firestarman** [comment] 2021-12-23 03:07
> I would say that the first step is to figure out why it is being generated. It started appearing locally for me pretty recently (last 1-2 weeks). I don't know if this is just appearing for me or for others as well, so that would be good to know.

Do you have GDS driver installed on your machine ?  It is possibly generated during running the `RapidsGdsStoreSuite` tests.

**Comment by andygrove** [comment] 2022-01-12 15:49
I just confirmed that the file does appear during `RapidsGdsStoreSuite`, which does run for me locally when I run `mvn clean verify`:

```
RapidsGdsStoreSuite:
- single shot spill with shared path
- single shot spill with exclusive path
- batch spill
```

I wasn't aware (or have forgotten) that I had installed the GDS driver.

**Comment by revans2** [comment] 2022-01-12 16:27
I think GDS is being installed by default with CUDA 11.5

**Comment by jlowe** [comment] 2022-01-18 18:02
If this file is appearing only when using cuFile then I think this is very low priority at this point.  We do not use cuFile in a typical setup. Moving this out of 22.02.

**Closed** 2024-02-28 21:37 UTC
Labels: bug
